export const hats = [
    {
        name: 'Royal Crown',
        hat: 'RoyalCrown',
        material1: 'Gold_Ore', qt1:'2',
        material2: 'Jewelers_Loupe', qt2: '2',
        material3: 'Spectral_Essence', qt3: '4',
    },
    {
        name: 'Santa Hat',
        hat: 'SantaHat',
        material1: 'Red_Cloth', qt1: '3',
        material2: 'Spectral_Essence', qt2: '4',
        material3: 'Treants_Flower', qt3: '1',
    },
    {
        name: 'Buccaneer Hat',
        hat: 'PirateHat',
        material1: 'Spectral_Essence', qt1: '4',
        material2: 'Treants_Flower', qt2: '3',
        material3: 'Buccaneer_Leather', qt3: '2',
    },
    {
        name: 'PumpkinHat',
        hat: 'Pumpkin',
        material1: 'Spectral_Essence', qt1: '4',
        material2: 'Treants_Flower', qt2: '3',
        material3: 'Trickster_Seed', qt3: '2',
    },
    {
        name: 'Halo Standard',
        hat: 'HaloNormal',
        material1: 'Gold_Ore', qt1: '4',
        material2: 'Jewelers_Loupe', qt2: '2',
        material3: 'Floatstone', qt3: '4',
    },
    {
        name: 'Fire Halo',
        hat: 'Fire',
        material1: 'Jewelers_Loupe', qt1: '3',
        material2: 'Floatstone', qt2: '4',
        material3: 'Brimstone', qt3: '2',
    },
    {
        name: 'Electric Halo',
        hat: 'ElectricHalo',
        material1: 'White_Ore', qt1: '2',
        material2: 'Floatstone', qt2: '5',
        material3: 'Jewelers_Loupe', qt3: '4',
    },
    {
        name: 'Red Party Hat',
        hat: 'PartyHat_Red',
        material1: 'Red_Cloth', qt1: '2',
        material2: 'Treants_Flower', qt2: '2',
        material3: 'Halcyion_Thread', qt3: '3',
    },
    {
        name: 'Blue Party Hat',
        hat: 'PartyHat_Blue',
        material1: 'Blue_Cloth', qt1: '2',
        material2: 'Treants_Flower', qt2: '2',
        material3: 'Halcyion_Thread', qt3: '3',
    },
    {
        name: 'Gold Party Hat',
        hat: 'PartyHat_Yellow copy 3',
        material1: 'Gold_Cloth', qt1: '4',
        material2: 'Treants_Flower', qt2: '2',
        material3: 'Halcyion_Thread', qt3: '4',
    },
]