export const heroTabs = [
  'ALL',
  'ASSASSINS',
  'MAGE',
  'PROTECTOR',
  'SNIPER',
  'WARRIOR',
]

export const heroCards = [
  {
    name: 'Ylva',
    type: ['JUNGLE', 'ASSASSIN'],
    description: 'A huntress that stalks her prey and lays traps for them.',
    spotlight: 'K6kHZW3Vq2g',
    stats: [
      { name: 'HEALTH', value: '703 - 2107', color: '#4eec8b' },
      { name: 'HEALTH REGEN', value: '(+)', color: '#4eec8b' },
      { name: 'ENERGY', value: '203 - 610', color: '#5bbcff' },
      { name: 'ENERGY REGEN', value: '(+)', color: '#5bbcff' },
      { name: 'WEAPON DAMAGE', value: '70 - 125', color: '#f48596' },
      { name: 'ATTACK SPEED', value: '100% - 136.3%', color: '#f48596' },
      { name: 'ARMOR', value: '25 - 75', color: '#f6ee71' },
      { name: 'SHIELD', value: '20 - 55', color: '#f6ee71' },
      { name: 'ATTACK RANGE', value: '5.5', color: '#e19efb' },
      { name: 'MOVE SPEED', value: '3.6', color: '#e19efb' },
    ],
    skills: [
      {
        name: 'Hunter’s Sense',
        type: 'Perk',
        image: 'Ylva-P',
        text: [
          'Ylva can detect the location and movement direction of enemy heroes through walls and brush, as long as they are moving and within her vision range.',
        ],
        video: 'Ylva-P',
        stats: [],
      },
      {
        name: 'Charge Shot',
        type: 'A ABILITY',
        image: 'Ylva-A',
        text: [
          'Ylva charges her weapon, causing her next basic attack to deal bonus damage based on the time spent charging. After it reaches full charge the attack will also stun. While active, Ylva is slowed. Reactivate to cancel.',
          '• Overdrive: At max rank, the time it takes to reach full charge is reduced.',
        ],
        video: 'Ylva-A',
        stats: [
          {
            name: 'Cooldown',
            amount: ['8s', '7.5s', '7s', '6.5s', '6s'],
            cr: '',
            wr: '',
          },
          {
            name: 'Energy Cost',
            amount: ['25', '30', '35', '40', '45'],
            cr: '',
            wr: '',
          },
          {
            name: 'Damage',
            amount: ['0', '0', '0', '0', '0'],
            cr: '',
            wr: '100%',
          },
          {
            name: 'Bonus Damage',
            amount: ['80', '120', '160', '200', '240'],
            cr: '100%',
            wr: '',
          },
          {
            name: 'Bonus Range',
            amount: ['0', '0', '0', '0', '0'],
            cr: '',
            wr: '',
          },
          {
            name: 'Stun Duration',
            amount: ['1s', '1s', '1s', '1s', '1s'],
            cr: '',
            wr: '',
          },
          {
            name: 'Charge Time',
            amount: ['1.6s', '1.6s', '1.6s', '1.6s', '1.2s'],
            cr: '',
            wr: '',
          },
          {
            name: 'Duration',
            amount: ['6s', '6s', '6s', '6s', '6s'],
            cr: '',
            wr: '',
          },
        ],
      },
      {
        name: 'Crimson Fang',
        type: 'B ABILITY',
        image: 'Ylva-B',
        text: [
          'Ylva lunges at her target to deliver a powerful strike that deals more damage to immobilized targets. She then gains additional move and attack speed for a short duration.',
          '• Overdrive: At max rank, lunge range is increased.',
        ],
        video: 'Ylva-B',
        stats: [
          {
            name: 'Cooldown',
            amount: ['10s', '9.5s', '9s', '8.5s', '8s'],
            cr: '',
            wr: '',
          },
          {
            name: 'Energy Cost',
            amount: ['25', '30', '35', '40', '45'],
            cr: '',
            wr: '',
          },
          {
            name: 'Damage',
            amount: ['140', '190', '240', '290', '390'],
            cr: '175%',
            wr: '140%',
          },
          {
            name: 'Range',
            amount: ['5.5', '5.5', '5.5', '5.5', '7.5'],
            cr: '',
            wr: '',
          },
          {
            name: 'Bonus Move Speed Duration',
            amount: ['3s', '3s', '3s', '3s', '3s'],
            cr: '',
            wr: '',
          },
          {
            name: 'Bonus Attack Speed',
            amount: ['40%', '40%', '40%', '40%', '40%'],
            cr: '',
            wr: '',
          },
          {
            name: 'Bonus Move Speed',
            amount: ['1', '1', '1', '1', '1'],
            cr: '',
            wr: '',
          },
          {
            name: 'Duration',
            amount: ['6s', '6s', '6s', '6s', '6s'],
            cr: '',
            wr: '',
          },
        ],
      },
      {
        name: 'VERSE OF JUDGEMENT',
        type: 'ULTIMATE',
        image: 'Ylva-C',
        text: [
          'Ylva places a mine that arms and stealths. When an enemy hero touches it, it will explode after a short delay, causing all enemies within range to take damage and become rooted. Only 1 trap can exist at once.',
          '• Traps expire after a minute. Basic attacks reduce their remaining duration.',
        ],
        video: 'Ylva-C',
        stats: [
          {
            name: 'Cooldown',
            amount: ['25s', '20s', '15s'],
            cr: '',
            wr: '',
          },
          {
            name: 'Energy Cost',
            amount: ['50', '60', '70'],
            cr: '',
            wr: '',
          },
          {
            name: 'Damage',
            amount: ['300', '450', '600'],
            cr: '150%',
            wr: '',
          },
          {
            name: 'Trap Limit',
            amount: ['1', '1', '1'],
            cr: '',
            wr: '',
          },
          {
            name: 'Root Duration',
            amount: ['1.6s', '1.8s', '2s'],
            cr: '',
            wr: '',
          },
          {
            name: 'Bonus Attack Speed',
            amount: ['40%', '40%', '40%', '40%', '40%'],
            cr: '',
            wr: '',
          },
          {
            name: 'Bonus Move Speed',
            amount: ['1', '1', '1', '1', '1'],
            cr: '',
            wr: '',
          },
          {
            name: 'Duration',
            amount: ['6s', '6s', '6s', '6s', '6s'],
            cr: '',
            wr: '',
          },
        ],
      },
    ],
    talents: [
      {
        name: 'SWIFT SHOT',
        type: 'Rare',
        color: '#6393F9',
        text: [
          'Charge Shot (A) reaches full charge faster.',
          '• Charge Time 80%',
          '• Cooldown 100%',
          '• Damage 100%',
        ],
      },
      {
        name: 'MULTY MINE',
        type: 'Epic',
        color: '#7A02EA',
        text: [
          'Ylva may place up to 3 Blinding Mines (Ult).',
          '• Trap Limit 3',
          '• Cooldown 80%',
          '• Damage 75%',
          '• Bonus Range 6',
        ],
        image: '',
      },
      {
        name: 'SHATTERED FANG',
        type: 'Legendary',
        color: '#FF9000',
        text: [
          'Ylva places a Blinding Mine (Ult) at her feet after using Crimson Fang (B). ',
          '• Cooldown 90%',
          '• Damage 100%',
        ],
        image: '',
      },
    ],
    // { name: '', type: '', color: '', image: '' }
    skins: [],
  },
  { name: 'Adagio', type: ['JUNGLE', 'PROTECTOR'] },
  { name: 'Alpha', type: ['JUNGLE', 'WARRIOR'] },
  { name: 'Anka', type: ['LANE', 'ASSASSIN'] },
  { name: 'Ardan', type: ['JUNGLE', 'PROTECTOR'] },
  { name: 'Baptiste', type: ['JUNGLE', 'MAGE'] },
  { name: 'Baron', type: ['LANE', 'SNIPER'] },
  { name: 'Blackfeather', type: ['LANE', 'ASSASSIN'] },
  { name: 'Catherine', type: ['JUNGLE', 'PROTECTOR'] },
  { name: 'Celeste', type: ['LANE', 'MAGE'] },
  { name: 'Churnwalker', type: ['JUNGLE', 'WARRIOR'] },
  { name: 'Flicker', type: ['JUNGLE', 'PROTECTOR'] },
  { name: 'Fortress', type: ['JUNGLE', 'PROTECTOR'] },
  { name: 'Glaive', type: ['JUNGLE', 'WARRIOR'] },
  { name: 'Grace', type: ['JUNGLE', 'PROTECTOR'] },
  { name: 'Grumpjaw', type: ['JUNGLE', 'WARRIOR'] },
  { name: 'Gwen', type: ['LANE', 'SNIPER'] },
  { name: 'Idris', type: ['JUNGLE', 'ASSASSIN'] },
  { name: 'Inara', type: ['JUNGLE', 'WARRIOR'] },
  { name: 'Joule', type: ['LANE', 'WARRIOR'] },
  { name: 'Kensei', type: ['LANE', 'JUNGLE', 'ASSASSIN'] },
  { name: 'Kestrel', type: ['JUNGLE', 'SNIPER'] },
  { name: 'Kinetic', type: ['LANE', 'MAGE'] },
  { name: 'Koshka', type: ['JUNGLE', 'ASSASSIN'] },
  { name: 'Krul', type: ['JUNGLE', 'WARRIOR'] },
  { name: 'Lance', type: ['JUNGLE', 'PROTECTOR'] },
  { name: 'Lorelai', type: ['JUNGLE', 'PROTECTOR'] },
  { name: 'Lyra', type: ['JUNGLE', 'PROTECTOR'] },
  { name: 'Magnus', type: ['LANE', 'MAGE'] },
  { name: 'Malene', type: ['LANE', 'MAGE'] },
  { name: 'Ozo', type: ['JUNGLE', 'ASSASSIN'] },
  { name: 'Petal', type: ['JUNGLE', 'SNIPER'] },
  { name: 'Phinn', type: ['JUNGLE', 'PROTECTOR'] },
  { name: 'Reim', type: ['JUNGLE', 'MAGE'] },
  { name: 'Reza', type: ['JUNGLE', 'ASSASSIN'] },
  { name: 'Ringo', type: ['LANE', 'SNIPER'] },
  { name: 'Rona', type: ['JUNGLE', 'WARRIOR'] },
  { name: 'Samuel', type: ['LANE', 'MAGE'] },
  { name: 'SAW', type: ['LANE', 'SNIPER'] },
  { name: 'Silvernail', type: ['LANE', 'SNIPER'] },
  { name: 'Skaarf', type: ['LANE', 'MAGE'] },
  { name: 'Skye', type: ['LANE', 'SNIPER'] },
  { name: 'Taka', type: ['JUNGLE', 'ASSASSIN'] },
  { name: 'Tony', type: ['JUNGLE', 'WARRIOR'] },
  { name: 'Varya', type: ['LANE', 'MAGE'] },
  { name: 'Vox', type: ['LANE', 'SNIPER'] },
  { name: 'Yates', type: ['JUNGLE', 'PROTECTOR'] },
]
