export const heroTabs = [
  'ALL',
  'ASSASSINS',
  'MAGE',
  'PROTECTOR',
  'SNIPER',
  'WARRIOR',
]

export const heroCards = [
  {
    name: 'Ylva',
    type: ['JUNGLE', 'ASSASSIN'],
    description: 'A huntress that stalks her prey and lays traps for them.',
    spotlight: 'K6kHZW3Vq2g',
    stats: [
      { name: 'HEALTH', value: '703 - 2107', color: '#4eec8b' },
      { name: 'HEALTH REGEN', value: '(+)', color: '#4eec8b' },
      { name: 'ENERGY', value: '203 - 610', color: '#5bbcff' },
      { name: 'ENERGY REGEN', value: '(+)', color: '#5bbcff' },
      { name: 'WEAPON DAMAGE', value: '70 - 125', color: '#f48596' },
      { name: 'ATTACK SPEED', value: '100% - 136.3%', color: '#f48596' },
      { name: 'ARMOR', value: '25 - 75', color: '#f6ee71' },
      { name: 'SHIELD', value: '20 - 55', color: '#f6ee71' },
      { name: 'ATTACK RANGE', value: '5.5', color: '#e19efb' },
      { name: 'MOVE SPEED', value: '3.6', color: '#e19efb' },
    ],
    skills: [
      {
        name: 'Hunter’s Sense',
        type: 'Perk',
        image: 'Ylva-P',
        text: [
          'Ylva can detect the location and movement direction of enemy heroes through walls and brush, as long as they are moving and within her vision range.',
        ],
        video: 'Ylva-P',
        stats: [],
      },
      {
        name: 'Charge Shot',
        type: 'A ABILITY',
        image: 'Ylva-A',
        text: [
          'Ylva charges her weapon, causing her next basic attack to deal bonus damage based on the time spent charging. After it reaches full charge the attack will also stun. While active, Ylva is slowed. Reactivate to cancel.',
          '• Overdrive: At max rank, the time it takes to reach full charge is reduced.',
        ],
        video: 'Ylva-A',
        stats: [
          {
            name: 'Cooldown',
            amount: ['8s', '7.5s', '7s', '6.5s', '6s'],
            cr: '',
            wr: '',
          },
          {
            name: 'Energy Cost',
            amount: ['25', '30', '35', '40', '45'],
            cr: '',
            wr: '',
          },
          {
            name: 'Damage',
            amount: ['0', '0', '0', '0', '0'],
            cr: '',
            wr: '100%',
          },
          {
            name: 'Bonus Damage',
            amount: ['80', '120', '160', '200', '240'],
            cr: '100%',
            wr: '',
          },
          {
            name: 'Bonus Range',
            amount: ['0', '0', '0', '0', '0'],
            cr: '',
            wr: '',
          },
          {
            name: 'Stun Duration',
            amount: ['1s', '1s', '1s', '1s', '1s'],
            cr: '',
            wr: '',
          },
          {
            name: 'Charge Time',
            amount: ['1.6s', '1.6s', '1.6s', '1.6s', '1.2s'],
            cr: '',
            wr: '',
          },
          {
            name: 'Duration',
            amount: ['6s', '6s', '6s', '6s', '6s'],
            cr: '',
            wr: '',
          },
        ],
      },
      {
        name: 'Crimson Fang',
        type: 'B ABILITY',
        image: 'Ylva-B',
        text: [
          'Ylva lunges at her target to deliver a powerful strike that deals more damage to immobilized targets. She then gains additional move and attack speed for a short duration.',
          '• Overdrive: At max rank, lunge range is increased.',
        ],
        video: 'Ylva-B',
        stats: [
          {
            name: 'Cooldown',
            amount: ['10s', '9.5s', '9s', '8.5s', '8s'],
            cr: '',
            wr: '',
          },
          {
            name: 'Energy Cost',
            amount: ['25', '30', '35', '40', '45'],
            cr: '',
            wr: '',
          },
          {
            name: 'Damage',
            amount: ['140', '190', '240', '290', '390'],
            cr: '175%',
            wr: '140%',
          },
          {
            name: 'Range',
            amount: ['5.5', '5.5', '5.5', '5.5', '7.5'],
            cr: '',
            wr: '',
          },
          {
            name: 'Bonus Move Speed Duration',
            amount: ['3s', '3s', '3s', '3s', '3s'],
            cr: '',
            wr: '',
          },
          {
            name: 'Bonus Attack Speed',
            amount: ['40%', '40%', '40%', '40%', '40%'],
            cr: '',
            wr: '',
          },
          {
            name: 'Bonus Move Speed',
            amount: ['1', '1', '1', '1', '1'],
            cr: '',
            wr: '',
          },
          {
            name: 'Duration',
            amount: ['6s', '6s', '6s', '6s', '6s'],
            cr: '',
            wr: '',
          },
        ],
      },
      {
        name: 'VERSE OF JUDGEMENT',
        type: 'ULTIMATE',
        image: 'Ylva-C',
        text: [
          'Ylva places a mine that arms and stealths. When an enemy hero touches it, it will explode after a short delay, causing all enemies within range to take damage and become rooted. Only 1 trap can exist at once.',
          '• Traps expire after a minute. Basic attacks reduce their remaining duration.',
        ],
        video: 'Ylva-C',
        stats: [
          {
            name: 'Cooldown',
            amount: ['25s', '20s', '15s'],
            cr: '',
            wr: '',
          },
          {
            name: 'Energy Cost',
            amount: ['50', '60', '70'],
            cr: '',
            wr: '',
          },
          {
            name: 'Damage',
            amount: ['300', '450', '600'],
            cr: '150%',
            wr: '',
          },
          {
            name: 'Trap Limit',
            amount: ['1', '1', '1'],
            cr: '',
            wr: '',
          },
          {
            name: 'Root Duration',
            amount: ['1.6s', '1.8s', '2s'],
            cr: '',
            wr: '',
          },
          {
            name: 'Bonus Attack Speed',
            amount: ['40%', '40%', '40%', '40%', '40%'],
            cr: '',
            wr: '',
          },
          {
            name: 'Bonus Move Speed',
            amount: ['1', '1', '1', '1', '1'],
            cr: '',
            wr: '',
          },
          {
            name: 'Duration',
            amount: ['6s', '6s', '6s', '6s', '6s'],
            cr: '',
            wr: '',
          },
        ],
      },
    ],
    talents: [
      {
        name: 'SWIFT SHOT',
        type: 'Rare',
        color: '#6393F9',
        text: [
          'Charge Shot (A) reaches full charge faster.',
          '• Charge Time 80%',
          '• Cooldown 100%',
          '• Damage 100%',
        ],
      },
      {
        name: 'MULTY MINE',
        type: 'Epic',
        color: '#7A02EA',
        text: [
          'Ylva may place up to 3 Blinding Mines (Ult).',
          '• Trap Limit 3',
          '• Cooldown 80%',
          '• Damage 75%',
          '• Bonus Range 6',
        ],
        image: '',
      },
      {
        name: 'SHATTERED FANG',
        type: 'Legendary',
        color: '#FF9000',
        text: [
          'Ylva places a Blinding Mine (Ult) at her feet after using Crimson Fang (B). ',
          '• Cooldown 90%',
          '• Damage 100%',
        ],
        image: '',
      },
    ],
    // { name: '', type: '', color: '', image: '' }
    skins: [],
  },
  { name: 'Adagio', type: ['CAPTAIN', 'PROTECTOR'] },
  { name: 'Alpha', type: ['JUNGLE', 'WARRIOR'] },
  { name: 'Anka', type: ['LANE', 'ASSASSIN'] },
  { name: 'Ardan', type: ['CAPTAIN', 'PROTECTOR'] },
  { name: 'Baptiste', type: ['JUNGLE', 'MAGE'] },
  { name: 'Baron', type: ['LANE', 'SNIPER'] },
  { name: 'Blackfeather', type: ['LANE', 'ASSASSIN'] },
  { name: 'Catherine', type: ['CAPTAIN', 'PROTECTOR'] },
  { name: 'Celeste', type: ['LANE', 'MAGE'] },
  { name: 'Churnwalker', type: ['CAPTAIN', 'WARRIOR'] },
  { name: 'Flicker', type: ['CAPTAIN', 'PROTECTOR'] },
  { name: 'Fortress', type: ['CAPTAIN', 'PROTECTOR'] },
  { name: 'Glaive', type: ['JUNGLE', 'WARRIOR'] },
  { name: 'Grace', type: ['CAPTAIN', 'PROTECTOR'] },
  { name: 'Grumpjaw', type: ['JUNGLE', 'WARRIOR'] },
  { name: 'Gwen', type: ['LANE', 'SNIPER'] },
  { name: 'Idris', type: ['JUNGLE', 'ASSASSIN'] },
  { name: 'Inara', type: ['JUNGLE', 'WARRIOR'] },
  { name: 'Joule', type: ['LANE', 'WARRIOR'] },
  { name: 'Kensei', type: ['LANE', 'JUNGLE', 'ASSASSIN'] },
  { name: 'Kestrel', type: ['JUNGLE', 'SNIPER'] },
  { name: 'Kinetic', type: ['LANE', 'MAGE'] },
  { name: 'Koshka', type: ['JUNGLE', 'ASSASSIN'] },
  { name: 'Krul', type: ['JUNGLE', 'WARRIOR'] },
  { name: 'Lance', type: ['CAPTAIN', 'PROTECTOR'] },
  { name: 'Lorelai', type: ['CAPTAIN', 'PROTECTOR'] },
  { name: 'Lyra', type: ['CAPTAIN', 'PROTECTOR'] },
  { name: 'Magnus', type: ['LANE', 'MAGE'] },
  { name: 'Malene', type: ['LANE', 'MAGE'] },
  { name: 'Ozo', type: ['JUNGLE', 'ASSASSIN'] },
  { name: 'Petal', type: ['JUNGLE', 'SNIPER'] },
  { name: 'Phinn', type: ['CAPTAIN', 'PROTECTOR'] },
  { name: 'Reim', type: ['JUNGLE', 'MAGE'] },
  { name: 'Reza', type: ['JUNGLE', 'ASSASSIN'] },
  { name: 'Ringo', type: ['LANE', 'SNIPER'] },
  { name: 'Rona', type: ['JUNGLE', 'WARRIOR'] },
  { name: 'Samuel', type: ['LANE', 'MAGE'] },
  { name: 'SAW', type: ['LANE', 'SNIPER'] },
  {
    name: 'Silvernail',
    type: ['LANE', 'SNIPER'],
    description: 'Grizzled hunter with a powerful crossbow and tripwires.',
    spotlight: 'cC5-fdOn8C8',
    stats: [
      { name: 'HEALTH', value: '745 - 2175', color: '#4eec8b' },
      { name: 'HEALTH REGEN', value: '-', color: '#4eec8b' },
      { name: 'ENERGY', value: '203 - 610', color: '#5bbcff' },
      { name: 'ENERGY REGEN', value: '-', color: '#5bbcff' },
      { name: 'WEAPON DAMAGE', value: '74 - 145', color: '#f48596' },
      { name: 'ATTACK SPEED', value: '100% - 136.3%', color: '#f48596' },
      { name: 'ARMOR', value: '25 - 75', color: '#f6ee71' },
      { name: 'SHIELD', value: '20 - 55', color: '#f6ee71' },
      { name: 'ATTACK RANGE', value: '6.2', color: '#e19efb' },
      { name: 'MOVE SPEED', value: '3.5', color: '#e19efb' },
    ],
    model: [{ image: 'Silvernailblurred' }, { tmodel: 'Silvernail' }],
    skills: [
      {
        name: 'DOUBLE SHOT',
        type: 'Perk',
        image: 'Silvernail-P',
        text: [
          'Silvernail loads an extra bolt every 4s-3s (level 1-12) which can be expended to chain a follow-up basic attack, dealing 60% damage.',
          '• Attack speed reduces load time.',
        ],
        video: 'Silvernail-P',
        stats: [],
      },
      {
        name: 'STAKE',
        type: 'A ABILITY',
        image: 'Silvernail-A',
        text: [
          'Silvernail plants an inactive Stake into the ground. Tripwires form between nearby inactive Stakes, activating the Stakes.',
          'Tripwire: Enemies crossing through will be briefly slowed, silenced, and take damage.',
          '• Silvernail can maintain up to 3 inactive Stakes at a time.',
          '• This ability has 2 charges.',
        ],
        video: 'Silvernail-A',
        stats: [
          // {
          //   name: 'Cooldown',
          //   amount: ['8s', '7.5s', '7s', '6.5s', '6s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Energy Cost',
          //   amount: ['25', '30', '35', '40', '45'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Damage',
          //   amount: ['0', '0', '0', '0', '0'],
          //   cr: '',
          //   wr: '100%',
          // },
          // {
          //   name: 'Bonus Damage',
          //   amount: ['80', '120', '160', '200', '240'],
          //   cr: '100%',
          //   wr: '',
          // },
          // {
          //   name: 'Bonus Range',
          //   amount: ['0', '0', '0', '0', '0'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Stun Duration',
          //   amount: ['1s', '1s', '1s', '1s', '1s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Charge Time',
          //   amount: ['1.6s', '1.6s', '1.6s', '1.6s', '1.2s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Duration',
          //   amount: ['6s', '6s', '6s', '6s', '6s'],
          //   cr: '',
          //   wr: '',
          // },
        ],
      },
      {
        name: 'CAUSTIC BLESSING',
        type: 'B ABILITY',
        image: 'Silvernail-B',
        text: ['Silvernail lobs a flask which damages, burns, and reveals enemies caught in the blast for 4s.',
        '• Refreshes Double Shot upon casting.',
        '• Deals 50% damage to minions.',],
        video: 'Silvernail-B',
        stats: [
          // {
          //   name: 'Cooldown',
          //   amount: ['10s', '9.5s', '9s', '8.5s', '8s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Energy Cost',
          //   amount: ['25', '30', '35', '40', '45'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Damage',
          //   amount: ['140', '190', '240', '290', '390'],
          //   cr: '175%',
          //   wr: '140%',
          // },
          // {
          //   name: 'Range',
          //   amount: ['5.5', '5.5', '5.5', '5.5', '7.5'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Bonus Move Speed Duration',
          //   amount: ['3s', '3s', '3s', '3s', '3s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Bonus Attack Speed',
          //   amount: ['40%', '40%', '40%', '40%', '40%'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Bonus Move Speed',
          //   amount: ['1', '1', '1', '1', '1'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Duration',
          //   amount: ['6s', '6s', '6s', '6s', '6s'],
          //   cr: '',
          //   wr: '',
          // },
        ],
      },
      {
        name: 'REBUKE',
        type: 'ULTIMATE',
        image: 'Silvernail-C',
        text: [
          "Passive: Double Shot damage increased.",
          "Activate: Silvernail fires a piercing bolt, dealing damage to and dragging enemies along with it.",
          "• Enemies who collide with a Tripwire, wall, or structure are stunned and take bonus damage."
        ],
        video: 'Silvernail-C',
        stats: [
          // {
          //   name: 'Cooldown',
          //   amount: ['25s', '20s', '15s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Energy Cost',
          //   amount: ['50', '60', '70'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Damage',
          //   amount: ['300', '450', '600'],
          //   cr: '150%',
          //   wr: '',
          // },
          // {
          //   name: 'Trap Limit',
          //   amount: ['1', '1', '1'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Root Duration',
          //   amount: ['1.6s', '1.8s', '2s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Bonus Attack Speed',
          //   amount: ['40%', '40%', '40%', '40%', '40%'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Bonus Move Speed',
          //   amount: ['1', '1', '1', '1', '1'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Duration',
          //   amount: ['6s', '6s', '6s', '6s', '6s'],
          //   cr: '',
          //   wr: '',
          // },
        ],
      },
    ],
    talents: [
      {
        name: 'Bolt Action',
        type: 'Rare',
        color: '#6393F9',
        text: ["Double Shot (Perk) fires an extra bolt. Rebuke (Ult) has increased range.", "• Cooldown 80% (-2%)", "• Damage 50% (+7.5%)", "• Bonus Range 1 (+0.2)"],
      },
      {
        name: 'Caustic Bounty',
        type: 'Epic',
        color: '#7A02EA',
        text: ["Caustic Blessing (B) throws two additional flasks.", "• Cooldown 90%", "• Damage 60%"],
      },
      {
        name: 'Tri-Wire',
        type: 'Legendary',
        color: '#FF9000',
        text: ["Stake (A) forms a tripwire triangle around target location..", "• Damage 100%", "• Duration 40%"],
      },
    ],
    skins: [
      {
        name: 'Tribal Silvernail',
        color: '#6393F9',
        type: 'Rare',
        image: 'Silvernail_Tribal',
      },
    ],
  },
  {
    name: 'Skaarf',
    type: ['LANE', 'MAGE'],
    description: 'Spits long-range fireballs and incinerates entire teams.',
    spotlight: 'AlXyClywtNQ',
    stats: [
      { name: 'HEALTH', value: '638 - 2112', color: '#4eec8b' },
      { name: 'HEALTH REGEN', value: '3.55 - 7.4', color: '#4eec8b' },
      { name: 'ENERGY', value: '200 - 464', color: '#5bbcff' },
      { name: 'ENERGY REGEN', value: '1.33 - 3.09', color: '#5bbcff' },
      { name: 'WEAPON DAMAGE', value: '80 - 154', color: '#f48596' },
      { name: 'ATTACK SPEED', value: '100% - 122%', color: '#f48596' },
      { name: 'ARMOR', value: '25 - 75', color: '#f6ee71' },
      { name: 'SHIELD', value: '20 - 55', color: '#f6ee71' },
      { name: 'ATTACK RANGE', value: '5.5', color: '#e19efb' },
      { name: 'MOVE SPEED', value: '3.4', color: '#e19efb' },
    ],
    model: [{ image: 'Skaarfblurred' }, { tmodel: 'Skaarf' }],
    skills: [
      {
        name: 'FAN THE FLAMES',
        type: 'Perk',
        image: 'Skaarf-P',
        text: ["Skaarf's abilities burn targets and his basic attacks deal bonus crystal damage to burning targets.",
        "Burn: 8 damage per second for 4s.",
        "Basic attacks: 2% (+2% of crystal power) of the target's max health as crystal damage.",
        "• This damage can crit for 2x.",
        "• Deals reduced damage to Kraken and structures."],
        video: "https://www.vainglorygame.com/wp-content/uploads/2015/05/Skaarf-P-Fan-the-Flames.mp4",
        stats: [],
      },
      {
        name: 'SPITFIRE',
        type: 'A ABILITY',
        image: 'Skaarf-A',
        text: ["Skaarf spits a fireball that collides with the first hero, structure or boss monster it hits.",
        "• The fireball damages and passes through smaller minions.",
        "• Each time it passes through a unit, its damate is reduced to 85% of before.",
        "• Deals 50% less damage damage to minions."],
        video: "https://www.vainglorygame.com/wp-content/uploads/2015/05/Skaarf-A-Spitfire.mp4",
        stats: [
          // {
          //   name: 'Cooldown',
          //   amount: ['8s', '7.5s', '7s', '6.5s', '6s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Energy Cost',
          //   amount: ['25', '30', '35', '40', '45'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Damage',
          //   amount: ['0', '0', '0', '0', '0'],
          //   cr: '',
          //   wr: '100%',
          // },
          // {
          //   name: 'Bonus Damage',
          //   amount: ['80', '120', '160', '200', '240'],
          //   cr: '100%',
          //   wr: '',
          // },
          // {
          //   name: 'Bonus Range',
          //   amount: ['0', '0', '0', '0', '0'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Stun Duration',
          //   amount: ['1s', '1s', '1s', '1s', '1s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Charge Time',
          //   amount: ['1.6s', '1.6s', '1.6s', '1.6s', '1.2s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Duration',
          //   amount: ['6s', '6s', '6s', '6s', '6s'],
          //   cr: '',
          //   wr: '',
          // },
        ],
      },
      {
        name: 'GOOP',
        type: 'B ABILITY',
        image: 'Skaarf-B',
        text: ["Skaarf hurls a goop onto the target location. Enemies walking through the sticky substance are slowed. Any of Skaarf's flames will ignite the puddle, dealing burst damage and burning enemies over time.",
        "• A flaming puddle does not slow enemies as much as a goop puddle.",
        "• Deals half damage to minions and Kraken."],
        video: "https://www.vainglorygame.com/wp-content/uploads/2015/05/Skaarf-B-Goop.mp4",
        stats: [
          // {
          //   name: 'Cooldown',
          //   amount: ['10s', '9.5s', '9s', '8.5s', '8s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Energy Cost',
          //   amount: ['25', '30', '35', '40', '45'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Damage',
          //   amount: ['140', '190', '240', '290', '390'],
          //   cr: '175%',
          //   wr: '140%',
          // },
          // {
          //   name: 'Range',
          //   amount: ['5.5', '5.5', '5.5', '5.5', '7.5'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Bonus Move Speed Duration',
          //   amount: ['3s', '3s', '3s', '3s', '3s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Bonus Attack Speed',
          //   amount: ['40%', '40%', '40%', '40%', '40%'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Bonus Move Speed',
          //   amount: ['1', '1', '1', '1', '1'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Duration',
          //   amount: ['6s', '6s', '6s', '6s', '6s'],
          //   cr: '',
          //   wr: '',
          // },
        ],
      },
      {
        name: 'DRAGON BREATH',
        type: 'ULTIMATE',
        image: 'Skaarf-C',
        text: ["Skaarf inhales for 1.5s, then exhales a huge flames for 3s. Skaarf may move freely while spewing fire.",
       "• Skaarf gains a quick burst of move speed when exhaling.",
       "• While inhaling or exhaling, enemies moving against the current are slowed while allies moving with it are sped up.",
       "• Skaarf temporarily gains fortified health while channeling.",
       "• Deals 50% damage to non-heroes."],
        video: "https://www.vainglorygame.com/wp-content/uploads/2015/05/Skaarf-C-Dragons-Breath.mp4",
        stats: [
          // {
          //   name: 'Cooldown',
          //   amount: ['25s', '20s', '15s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Energy Cost',
          //   amount: ['50', '60', '70'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Damage',
          //   amount: ['300', '450', '600'],
          //   cr: '150%',
          //   wr: '',
          // },
          // {
          //   name: 'Trap Limit',
          //   amount: ['1', '1', '1'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Root Duration',
          //   amount: ['1.6s', '1.8s', '2s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Bonus Attack Speed',
          //   amount: ['40%', '40%', '40%', '40%', '40%'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Bonus Move Speed',
          //   amount: ['1', '1', '1', '1', '1'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Duration',
          //   amount: ['6s', '6s', '6s', '6s', '6s'],
          //   cr: '',
          //   wr: '',
          // },
        ],
      },
    ],
    talents: [
      {
        name: 'Splitfire',
        type: 'Rare',
        color: '#6393F9',
        text: ["Spitfire (A) shoots three fireballs in a cone.", "• Damage 60% (+2%)"],
      },
      {
        name: 'Flash Fire',
        type: 'Epic',
        color: '#7A02EA',
        text: ["Dragon Breath (Ult) has a quicker start but shorter duration.", "• Cooldown 60% (-3%)", "• Damage 110% (+10%)"],
      },
      {
        name: 'Flaming Sludge',
        type: 'Legendary',
        color: '#FF9000',
        text: ["Spitfire (A) creates a Goop (B) pool when it expires.", "• Spitfire Damage 30% (+5%)", "• Burning Goop Damage 60% (+10%)", "• Range 9"],
      },
    ],
    skins: [
      {
        name: 'Water Dragon Skaarf',
        color: '#6393F9',
        type: 'Rare',
        image: 'Skaarf_Water_Dragon',
      },
      {
        name: 'Cloud Dragon Skaarf',
        color: '#7A02EA',
        type: 'Epic',
        image: 'Skaarf_Cloud_Dragon',
      },
      {
        name: 'Ice Dragon Skaarf',
        color: '#FF9000',
        type: 'Legendary',
        image: 'Skaarf_Ice_Dragon',
      },
      {
        name: 'Rainbow Skaarf',
        color: '#FF9000',
        type: 'Legendary',
        image: 'Skaarf_Rainbow_White',
      },
      {
        name: 'Rainbow Tabby Skaarf',
        color: 'red',
        type: 'Special Edition',
        image: 'Skaarf_Rainbow_Tabby',
      },
      {
        name: 'Rainbow Bengal Skaarf',
        color: 'red',
        type: 'Special Edition',
        image: 'Skaarf_Rainbow_Bengal',
      },
      {
        name: 'Green Sparkler Skaarf',
        color: 'red',
        type: 'Special Edition',
        image: 'Skaarf_Sparkler_Green_SE',
      },
      {
        name: 'Purple Sparkler Skaarf',
        color: 'red',
        type: 'Special Edition',
        image: 'Skaarf_Sparkler_Purple_SE',
      },{
        name: 'Blue Sparkler Skaarf',
        color: 'red',
        type: 'Special Edition',
        image: 'Skaarf_Sparkler_Blue_SE',
      },
      {
        name: 'Red Sparkler Skaarf',
        color: 'red',
        type: 'Special Edition',
        image: 'Skaarf_Sparkler_Red_SE',
      },
      {
        name: 'Gold Sparkler Skaarf',
        color: 'red',
        type: 'Special Edition',
        image: 'Skaarf_Sparkler_Gold_SE',
      },
    ],
  },
  {
    name: 'Skye',
    type: ['LANE', 'SNIPER'],
    description: 'Versatile, elusive mech pilot who can flank enemies from any angle.',
    spotlight: 'N2Ll7RmMnXs',
    stats: [
      { name: 'HEALTH', value: '708 - 2100', color: '#4eec8b' },
      { name: 'HEALTH REGEN', value: ' - ', color: '#4eec8b' },
      { name: 'ENERGY', value: '380 - 732', color: '#5bbcff' },
      { name: 'ENERGY REGEN', value: ' - ', color: '#5bbcff' },
      { name: 'WEAPON DAMAGE', value: '72 - 111', color: '#f48596' },
      { name: 'ATTACK SPEED', value: '100% - 136.3%', color: '#f48596' },
      { name: 'ARMOR', value: '25 - 75', color: '#f6ee71' },
      { name: 'SHIELD', value: '20 - 55', color: '#f6ee71' },
      { name: 'ATTACK RANGE', value: '6.1', color: '#e19efb' },
      { name: 'MOVE SPEED', value: '3.2', color: '#e19efb' },
    ],
    model: [{ image: 'Skyeblurred' }, { tmodel: 'Skye' }],
    skills: [
      {
        name: 'TARGET LOCK',
        type: 'Perk',
        image: 'Skye-P',
        text: ["Skye's basic attacks apply Target Lock to the last target.",
        "• Basic attacks and Forward Barrage on that locked target grant her up to +2 move speed for 1.2s, but this boost is much weaker while moving backward.",
        "• Target Lock lasts 3s and is lost when the target is more than 8.5 meters away."],
        video: "https://www.vainglorygame.com/wp-content/uploads/2015/09/P-Skye-Target-Lock-Large.mp4",
        stats: [],
      },
      {
        name: 'FORWARD BARRAGE',
        type: 'A ABILITY',
        image: 'Skye-A',
        text: ["Skye fires a continuous stream of bullets while strafing in the selected direction for 3s. Building weapon power makes the barrage slow approaching enemies by up to 40%.",
        "• Reactivate this ability to stop firing.",
        "• Deals bonus damage to locked target.",
        "• Deals 50% less damage to structures and bosses."],
        video: "https://www.vainglorygame.com/wp-content/uploads/2015/09/A-Skye-Forward-Barrage-Large.mp4",
        stats: [
          // {
          //   name: 'Cooldown',
          //   amount: ['8s', '7.5s', '7s', '6.5s', '6s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Energy Cost',
          //   amount: ['25', '30', '35', '40', '45'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Damage',
          //   amount: ['0', '0', '0', '0', '0'],
          //   cr: '',
          //   wr: '100%',
          // },
          // {
          //   name: 'Bonus Damage',
          //   amount: ['80', '120', '160', '200', '240'],
          //   cr: '100%',
          //   wr: '',
          // },
          // {
          //   name: 'Bonus Range',
          //   amount: ['0', '0', '0', '0', '0'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Stun Duration',
          //   amount: ['1s', '1s', '1s', '1s', '1s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Charge Time',
          //   amount: ['1.6s', '1.6s', '1.6s', '1.6s', '1.2s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Duration',
          //   amount: ['6s', '6s', '6s', '6s', '6s'],
          //   cr: '',
          //   wr: '',
          // },
        ],
      },
      {
        name: 'SURI STRIKE',
        type: 'B ABILITY',
        image: 'Skye-B',
        text: ["Skye dashes to a chosen location around her locked target while firing a volley of missiles along a line between her and her target.",
        "• Multiple missles can hit the same target, but subsequent hits deal 20% damage.",
        "• This ability can only be activated when Skye has a locked target.",
        "• Activation this ability resets a portion of the cooldown on Forward Barrage.",
        "• Passive: Each ability point in Suri Strike increases the duration of Target Lock.",
        "• Deals 50% less damage to minions."],
        video: 'Skye-B',
        stats: [
          // {
          //   name: 'Cooldown',
          //   amount: ['10s', '9.5s', '9s', '8.5s', '8s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Energy Cost',
          //   amount: ['25', '30', '35', '40', '45'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Damage',
          //   amount: ['140', '190', '240', '290', '390'],
          //   cr: '175%',
          //   wr: '140%',
          // },
          // {
          //   name: 'Range',
          //   amount: ['5.5', '5.5', '5.5', '5.5', '7.5'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Bonus Move Speed Duration',
          //   amount: ['3s', '3s', '3s', '3s', '3s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Bonus Attack Speed',
          //   amount: ['40%', '40%', '40%', '40%', '40%'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Bonus Move Speed',
          //   amount: ['1', '1', '1', '1', '1'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Duration',
          //   amount: ['6s', '6s', '6s', '6s', '6s'],
          //   cr: '',
          //   wr: '',
          // },
        ],
      },
      {
        name: 'DEATH FROM ABOVE',
        type: 'ULTIMATE',
        image: 'Skye-C',
        text: ["Skye fires a salvo of missiles at a chosen location around her locked target. After a 1.3s delay, the missiles rain down on that location, stunning enemies for 0.5s. Enemies still in the area afterward are slowed and take crystal damage.",
        "• Aiming directly on your locked target rains down the missiles in a cluster.",
        "• Aiming away from your locked target rains them down in a line across the target's path.",
        "• This ability can only be activated when Skye has a locked target.",
        "• Deals 50% less damage to structures and bosses.",
        "• Passive: Each ability point in Death from Above increases the range of Target Lock."],
        video: "https://www.vainglorygame.com/wp-content/uploads/2015/09/C-Skye-Death-From-Above-Large.mp4",
        stats: [
          // {
          //   name: 'Cooldown',
          //   amount: ['25s', '20s', '15s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Energy Cost',
          //   amount: ['50', '60', '70'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Damage',
          //   amount: ['300', '450', '600'],
          //   cr: '150%',
          //   wr: '',
          // },
          // {
          //   name: 'Trap Limit',
          //   amount: ['1', '1', '1'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Root Duration',
          //   amount: ['1.6s', '1.8s', '2s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Bonus Attack Speed',
          //   amount: ['40%', '40%', '40%', '40%', '40%'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Bonus Move Speed',
          //   amount: ['1', '1', '1', '1', '1'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Duration',
          //   amount: ['6s', '6s', '6s', '6s', '6s'],
          //   cr: '',
          //   wr: '',
          // },
        ],
      },
    ],
    talents: [
      {
        name: 'Enhanced Thrusters',
        type: 'Rare',
        color: '#6393F9',
        text: ["Sure Strike (B) grants Skye a move-speed bonus after completion. Skye passively gains crystal power.", "• Bonus Move Speed 1.5 (+0.1)", "• Bonus Move Speed Duration 3s", "• Passive Crystal Power +5% (+1.5%)"],
      },
      {
        name: 'Raining Death',
        type: 'Epic',
        color: '#7A02EA',
        text: ["Death from Above (Ult) has 1 additional charge.", "• Damage 115% (+15%)", "• Cooldown 70% (-2.5%)"],
      },
      {
        name: 'Piercing Barrage',
        type: 'Legendary',
        color: '#FF9000',
        text: ["Forward Barrage (A) pierces through enemies, damaging all in a line and has 2 bonus range.", "• Damage 100% (+10%)"],
      },
    ],
    skins: [
      {
        name: 'Air Combat Skye',
        color: '#6393F9',
        type: 'Rare',
        image: 'Skye_Air_Combat',
      },
      {
        name: 'Stealth Fighter Skye',
        color: '#7A02EA',
        type: 'Epic',
        image: 'Skye_Stealth_Fighter',
      },
      {
        name: 'Supersonic Skye',
        color: '#FF9000',
        type: 'Legendary',
        image: 'Skye_Supersonic',
      },
      {
        name: 'Ride or Die Skye',
        color: '#FF9000',
        type: 'Legendary',
        image: 'Skye_Ride_or_Die',
      },
    ],
  },
  {
    name: 'Taka',
    type: ['JUNGLE', 'ASSASSIN'],
    description: 'Stealthy assassin who can heal while invisible.',
    spotlight: 'Oo9Mu7cRRzA',
    stats: [
      { name: 'HEALTH', value: '702 - 2287', color: '#4eec8b' },
      { name: 'HEALTH REGEN', value: '3.51 - 7.36', color: '#4eec8b' },
      { name: 'ENERGY', value: '180 - 422', color: '#5bbcff' },
      { name: 'ENERGY REGEN', value: '1.33 - 3.09', color: '#5bbcff' },
      { name: 'WEAPON DAMAGE', value: '68 - 125', color: '#f48596' },
      { name: 'ATTACK SPEED', value: '100% - 136.3%', color: '#f48596' },
      { name: 'ARMOR', value: '30 - 85', color: '#f6ee71' },
      { name: 'SHIELD', value: '20 - 60', color: '#f6ee71' },
      { name: 'ATTACK RANGE', value: '2', color: '#e19efb' },
      { name: 'MOVE SPEED', value: '3.5', color: '#e19efb' },
    ],
    model: [{ image: 'Takablurred' }, { tmodel: 'Taka' }],
    skills: [
      {
        name: 'HOUSE KAMUHA',
        type: 'Perk',
        image: 'Taka-P',
        text: [
          'Taka gains Mortal Strike every 4s.',
          "• Mortal Strike: Taka's next basic attack deals 30-63 (level 1-12) (+35% weapon power) bonus damage and briefly gains bonus movement speed.",
          '• When Taka uses an ability or lands a Mortal Strike, he gains a stack of Ki.',
          '• Ki: Taka gains Mortal Strike faster and his ability cooldown are reduced by 10% per stack.',
          '• 5 stacks max.',
        ],
        video: 'Taka-P',
        stats: [],
      },
      {
        name: 'KAITEN',
        type: 'A ABILITY',
        image: 'Taka-A',
        text: [
          'Taka flips over his target, cutting it with his switchblade. Taka is invulnerable to damage & debuffs while in mid-air.',
        ],
        video: 'Taka-A',
        stats: [
          // {
          //   name: 'Cooldown',
          //   amount: ['8s', '7.5s', '7s', '6.5s', '6s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Energy Cost',
          //   amount: ['25', '30', '35', '40', '45'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Damage',
          //   amount: ['0', '0', '0', '0', '0'],
          //   cr: '',
          //   wr: '100%',
          // },
          // {
          //   name: 'Bonus Damage',
          //   amount: ['80', '120', '160', '200', '240'],
          //   cr: '100%',
          //   wr: '',
          // },
          // {
          //   name: 'Bonus Range',
          //   amount: ['0', '0', '0', '0', '0'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Stun Duration',
          //   amount: ['1s', '1s', '1s', '1s', '1s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Charge Time',
          //   amount: ['1.6s', '1.6s', '1.6s', '1.6s', '1.2s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Duration',
          //   amount: ['6s', '6s', '6s', '6s', '6s'],
          //   cr: '',
          //   wr: '',
          // },
        ],
      },
      {
        name: 'KAKU',
        type: 'B ABILITY',
        image: 'Taka-B',
        text: [
          'Taka throws a smoke bomb at his feet and becomes invisible. While stealthed, Taka moves faster and heals himself.',
          '• Invisibility ends early if he strikes a target or takes direct damage.',
          '• Turrets, Scout Traps and Flare Guns can still see Taka while he is invisible.',
        ],
        video: 'Taka-B',
        stats: [
          // {
          //   name: 'Cooldown',
          //   amount: ['10s', '9.5s', '9s', '8.5s', '8s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Energy Cost',
          //   amount: ['25', '30', '35', '40', '45'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Damage',
          //   amount: ['140', '190', '240', '290', '390'],
          //   cr: '175%',
          //   wr: '140%',
          // },
          // {
          //   name: 'Range',
          //   amount: ['5.5', '5.5', '5.5', '5.5', '7.5'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Bonus Move Speed Duration',
          //   amount: ['3s', '3s', '3s', '3s', '3s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Bonus Attack Speed',
          //   amount: ['40%', '40%', '40%', '40%', '40%'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Bonus Move Speed',
          //   amount: ['1', '1', '1', '1', '1'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Duration',
          //   amount: ['6s', '6s', '6s', '6s', '6s'],
          //   cr: '',
          //   wr: '',
          // },
        ],
      },
      {
        name: 'X-RETSU',
        type: 'ULTIMATE',
        image: 'Taka-C',
        text: [
          "Taka bursts through his target for massive damage and gains Ki Stacks. The target suffers a mortal wound (reduced healing) and takes damage per second for the next 3s. The wound's duration is refreshed whenever Taka Mortal Strikes this target.",
        ],
        video:
          '"https://www.vainglorygame.com/wp-content/uploads/2015/05/Taka-C-X-Retsu.mp4"',
        stats: [
          // {
          //   name: 'Cooldown',
          //   amount: ['25s', '20s', '15s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Energy Cost',
          //   amount: ['50', '60', '70'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Damage',
          //   amount: ['300', '450', '600'],
          //   cr: '150%',
          //   wr: '',
          // },
          // {
          //   name: 'Trap Limit',
          //   amount: ['1', '1', '1'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Root Duration',
          //   amount: ['1.6s', '1.8s', '2s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Bonus Attack Speed',
          //   amount: ['40%', '40%', '40%', '40%', '40%'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Bonus Move Speed',
          //   amount: ['1', '1', '1', '1', '1'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Duration',
          //   amount: ['6s', '6s', '6s', '6s', '6s'],
          //   cr: '',
          //   wr: '',
          // },
        ],
      },
    ],
    talents: [
      {
        name: 'Ranged Kaiten',
        type: 'Rare',
        color: '#6393F9',
        text: ['Kaiten (A) has 5 increased range.', '• Damage 125% (+4%)'],
      },
      {
        name: 'Protective Decoy',
        type: 'Epic',
        color: '#7A02EA',
        text: [
          'Kaku (B) grants Taka invulnerability for 0.8s.',
          '• Cooldown 70% (-2.5%)',
          '• Heal 110% (+4%)',
        ],
      },
      {
        name: 'Triple X-Retsu',
        type: 'Legendary',
        color: '#FF9000',
        text: [
          'X-Retsu (Ult) automatically chains to 3 targets.',
          '• Damage 80%',
        ],
      },
    ],
    skins: [
      {
        name: 'Little Fox Taka',
        color: '#6393F9',
        type: 'Rare',
        image: 'Taka_Little_Fox',
      },
      {
        name: 'Shiro Kage Taka',
        color: '#7A02EA',
        type: 'Epic',
        image: 'Taka_Shiro_Kage',
      },
      {
        name: 'White Ghost Taka',
        color: '#FF9000',
        type: 'Legendary',
        image: 'Taka_White_Ghost',
      },
      {
        name: 'School Days Taka',
        color: '#6393F9',
        type: 'Legendary',
        image: 'Taka_School_Days',
      },
      {
        name: 'Fury Taka',
        color: '#7A02EA',
        type: 'Epic',
        image: 'Taka_Fury',
      },
      {
        name: 'Night Shadow Taka',
        color: 'red',
        type: 'Special Edition',
        image: 'Taka_Night_Shadow_SE',
      },
      {
        name: 'Night Shadow Taka',
        color: '#FADA5E',
        type: 'Limited Edition',
        image: 'Taka_Night_Shadow_LE',
      },
      {
        name: 'Wu Xing Flame Taka',
        color: 'red',
        type: 'Special Edition',
        image: 'Taka_Wu_Xing_Flame',
      },
    ],
  },
  {
    name: 'Tony',
    type: ['JUNGLE', 'WARRIOR'],
    description: 'Dwarven brawler who taunts and pummels enemies.',
    spotlight: 'HG-_NNyu4I8',
    stats: [
      { name: 'HEALTH', value: '762 - 2544', color: '#4eec8b' },
      { name: 'HEALTH REGEN', value: '4.01 - 7.42', color: '#4eec8b' },
      { name: 'ENERGY', value: '280 - 643', color: '#5bbcff' },
      { name: 'ENERGY REGEN', value: '1.87 - 4.29', color: '#5bbcff' },
      { name: 'WEAPON DAMAGE', value: '79 - 1.64', color: '#f48596' },
      { name: 'ATTACK SPEED', value: '100% - 136.3%', color: '#f48596' },
      { name: 'ARMOR', value: '30 - 85', color: '#f6ee71' },
      { name: 'SHIELD', value: '20 - 60', color: '#f6ee71' },
      { name: 'ATTACK RANGE', value: '1.7', color: '#e19efb' },
      { name: 'MOVE SPEED', value: '3.5', color: '#e19efb' },
    ],
    model: [{ image: 'Tonyblurred' }, { tmodel: 'Tony' }],
    skills: [
      {
        name: 'COME AT ME',
        type: 'Perk',
        image: 'Tony-P',
        text: [
          'When Tony receives damage, he gains 60-302 (level 1-12) (+20% of his bonus health) health barrier for 2s. This cannot occur again within 12s-6.5s (level 1-12).',
        ],
        video: 'Tony-P',
        stats: [],
      },
      {
        name: 'JAWBREAKER',
        type: 'A ABILITY',
        image: 'Tony-A',
        text: [
          'Tony’s next three basic attacks are empowered. These attacks launch Tony toward his target, dealing bonus damage. The third attack is a two-handed strike that will stun his target.',
          '• Tony also gains a decaying move speed bonus when activating this ability.',
        ],
        video: 'Tony-A',
        stats: [
          // {
          //   name: 'Cooldown',
          //   amount: ['8s', '7.5s', '7s', '6.5s', '6s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Energy Cost',
          //   amount: ['25', '30', '35', '40', '45'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Damage',
          //   amount: ['0', '0', '0', '0', '0'],
          //   cr: '',
          //   wr: '100%',
          // },
          // {
          //   name: 'Bonus Damage',
          //   amount: ['80', '120', '160', '200', '240'],
          //   cr: '100%',
          //   wr: '',
          // },
          // {
          //   name: 'Bonus Range',
          //   amount: ['0', '0', '0', '0', '0'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Stun Duration',
          //   amount: ['1s', '1s', '1s', '1s', '1s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Charge Time',
          //   amount: ['1.6s', '1.6s', '1.6s', '1.6s', '1.2s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Duration',
          //   amount: ['6s', '6s', '6s', '6s', '6s'],
          //   cr: '',
          //   wr: '',
          // },
        ],
      },
      {
        name: 'TRASH TALK',
        type: 'B ABILITY',
        image: 'Tony-B',
        text: [
          'Tony hurls insults in the target direction. All enemies hit receive damage and heroes are forced to attack Tony for 0.8s.',
          '• This also resets the cooldown of Come At Me, allowing it to trigger again.',
          '• Tony gains a 25% damage reduction while taunting.',
          '• The duration is further increased with weapon power up to a cap of 1.8s with 300 weapon power.',
        ],
        video: 'Tony-B',
        stats: [
          // {
          //   name: 'Cooldown',
          //   amount: ['10s', '9.5s', '9s', '8.5s', '8s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Energy Cost',
          //   amount: ['25', '30', '35', '40', '45'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Damage',
          //   amount: ['140', '190', '240', '290', '390'],
          //   cr: '175%',
          //   wr: '140%',
          // },
          // {
          //   name: 'Range',
          //   amount: ['5.5', '5.5', '5.5', '5.5', '7.5'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Bonus Move Speed Duration',
          //   amount: ['3s', '3s', '3s', '3s', '3s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Bonus Attack Speed',
          //   amount: ['40%', '40%', '40%', '40%', '40%'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Bonus Move Speed',
          //   amount: ['1', '1', '1', '1', '1'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Duration',
          //   amount: ['6s', '6s', '6s', '6s', '6s'],
          //   cr: '',
          //   wr: '',
          // },
        ],
      },
      {
        name: 'BADA BOOM',
        type: 'ULTIMATE',
        image: 'Tony-C',
        text: [
          'Tony winds up, then dashes to target location, releasing a massive uppercut. This colossal punch deals damage and knocks away all enemies caught in the area.',
        ],
        video: 'Tony-C',
        stats: [
          // {
          //   name: 'Cooldown',
          //   amount: ['25s', '20s', '15s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Energy Cost',
          //   amount: ['50', '60', '70'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Damage',
          //   amount: ['300', '450', '600'],
          //   cr: '150%',
          //   wr: '',
          // },
          // {
          //   name: 'Trap Limit',
          //   amount: ['1', '1', '1'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Root Duration',
          //   amount: ['1.6s', '1.8s', '2s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Bonus Attack Speed',
          //   amount: ['40%', '40%', '40%', '40%', '40%'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Bonus Move Speed',
          //   amount: ['1', '1', '1', '1', '1'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Duration',
          //   amount: ['6s', '6s', '6s', '6s', '6s'],
          //   cr: '',
          //   wr: '',
          // },
        ],
      },
    ],
    talents: [
      {
        name: 'Mighty Brawler',
        type: 'Rare',
        color: '#6393F9',
        text: [
          'Tony gains bonus attack speed and increased health barrier from Come At Me (Perk).',
          '• Attack Speed 10% (+2.5%)',
          '• Barrier 20% (+5%)',
        ],
      },
      {
        name: 'Haymakers',
        type: 'Epic',
        color: '#7A02EA',
        text: [
          'Tony’s Jawbreaker (A) now deals damage in an area around the target.',
          '• Bonus Damage 30% (+2.5%)',
        ],
      },
      {
        name: 'Doesn’t Even Hurt',
        type: 'Legendary',
        color: '#FF9000',
        text: [
          'Tony takes no damage from taunted targets.',
          '• Barrier Duration 1s',
        ],
      },
    ],
    skins: [
      {
        name: 'Steam Knight Tony',
        color: '#6393F9',
        type: 'Rare',
        image: 'Tony_SteamKnight',
      },
    ],
  },
  {
    name: 'Varya',
    type: ['LANE', 'MAGE'],
    description:
      'Shocking valkyrie who chains massive damage across enemy teams.',
    spotlight: 'dMBPEcWHgek',
    stats: [
      { name: 'HEALTH', value: '642 - 2127', color: '#4eec8b' },
      { name: 'HEALTH REGEN', value: '2.81 - 6.22', color: '#4eec8b' },
      { name: 'ENERGY', value: '950 - 1500', color: '#5bbcff' },
      { name: 'ENERGY REGEN', value: '36 - 64.6', color: '#5bbcff' },
      { name: 'WEAPON DAMAGE', value: '-', color: '#f48596' },
      { name: 'ATTACK SPEED', value: '100% - 115%', color: '#f48596' },
      { name: 'ARMOR', value: '25 - 75', color: '#f6ee71' },
      { name: 'SHIELD', value: '20 - 55', color: '#f6ee71' },
      { name: 'ATTACK RANGE', value: '6.2', color: '#e19efb' },
      { name: 'MOVE SPEED', value: '3.2', color: '#e19efb' },
    ],
    model: [{ image: 'Varyablurred' }, { tmodel: 'Varya' }],
    skills: [
      {
        name: 'CHAIN LIGHTNING',
        type: 'Perk',
        image: 'Varya-P',
        text: [
          "Varya's attacks deal 70-114 (level 1-12) (+25% Crystal Power) crystal damage. If Varya holds her ground after attacking, she will consume 170 energy to striker her target again and Chain Lightning up to 3 additional targets.",
          '• Chain Lightning: Deals 37-125 (level 1-12) (+50% Crystal Power) damage to each target.',
        ],
        video: 'Varya-P',
        stats: [],
      },
      {
        name: 'STORMFORGED SPEAR',
        type: 'A ABILITY',
        image: 'Varya-A',
        text: [
          'Varya throws a spear at lightning speed, striking the first enemy in its path. This deals a burst of damage to the target and chains additional damage to nearby targets.',
          '• When cast during or after Arc Recursion, the spear is thrown more quickly.',
          '• Number or additional targets hit is equal to her Chain Lighting attack.',
          '• The initial spear does not impact on lane minions.',
        ],
        video: 'Varya-A',
        stats: [
          // {
          //   name: 'Cooldown',
          //   amount: ['8s', '7.5s', '7s', '6.5s', '6s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Energy Cost',
          //   amount: ['25', '30', '35', '40', '45'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Damage',
          //   amount: ['0', '0', '0', '0', '0'],
          //   cr: '',
          //   wr: '100%',
          // },
          // {
          //   name: 'Bonus Damage',
          //   amount: ['80', '120', '160', '200', '240'],
          //   cr: '100%',
          //   wr: '',
          // },
          // {
          //   name: 'Bonus Range',
          //   amount: ['0', '0', '0', '0', '0'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Stun Duration',
          //   amount: ['1s', '1s', '1s', '1s', '1s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Charge Time',
          //   amount: ['1.6s', '1.6s', '1.6s', '1.6s', '1.2s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Duration',
          //   amount: ['6s', '6s', '6s', '6s', '6s'],
          //   cr: '',
          //   wr: '',
          // },
        ],
      },
      {
        name: 'ARC RECURSION',
        type: 'B ABILITY',
        image: 'Varya-B',
        text: [
          'After gathering power for 0.9s, Varya’s next two move commands will instantly dash in the chosen direction, striking the 3 nearest enemies at the end of each dash. For each enemy struck, Varya recovers 5% of her energy and gains a barrier equal to 3% of her health (bonuses doubled on heroes).',
          '• Overdrive: Varya moves further with each dash.',
          '• Varya can dash at any time, but will only dash once if she has not fully charged.',
          '• Varya can activate Stormforged Spear at any time during this ability. Any remaining dashes will trigger after the spear is thrown.',
          '• Deals 50% less damage to minions.',
        ],
        video: 'Varya-B',
        stats: [
          // {
          //   name: 'Cooldown',
          //   amount: ['10s', '9.5s', '9s', '8.5s', '8s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Energy Cost',
          //   amount: ['25', '30', '35', '40', '45'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Damage',
          //   amount: ['140', '190', '240', '290', '390'],
          //   cr: '175%',
          //   wr: '140%',
          // },
          // {
          //   name: 'Range',
          //   amount: ['5.5', '5.5', '5.5', '5.5', '7.5'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Bonus Move Speed Duration',
          //   amount: ['3s', '3s', '3s', '3s', '3s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Bonus Attack Speed',
          //   amount: ['40%', '40%', '40%', '40%', '40%'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Bonus Move Speed',
          //   amount: ['1', '1', '1', '1', '1'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Duration',
          //   amount: ['6s', '6s', '6s', '6s', '6s'],
          //   cr: '',
          //   wr: '',
          // },
        ],
      },
      {
        name: "ANVIL'S HAMMER",
        type: 'ULTIMATE',
        image: 'Varya-C',
        text: [
          'After channeling for 2.4s, Varya unleashes the fury of the storm, calling a series of lightning strikes on every enemy hero, regardless of distance. Passively, each rank of the ultimate permanently increases her attack speed and the number enemies her Chain Lightning and Stormforged Spear will hit.',
          '• Lightning strikes target the ground beneath enemy heroes, giving them an opportunity to move out of the way.',
          '• Lightning strikes deal 50% reduced damage to enemies already hit lightning in the same wave.',
          '• Varya can break out of channeling early by activating Stormforged Spear or Arc Recursion. This does not cancel the spell.',
          '• Deals 50% less damage to minions.',
        ],
        video: 'Varya-C',
        stats: [
          // {
          //   name: 'Cooldown',
          //   amount: ['25s', '20s', '15s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Energy Cost',
          //   amount: ['50', '60', '70'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Damage',
          //   amount: ['300', '450', '600'],
          //   cr: '150%',
          //   wr: '',
          // },
          // {
          //   name: 'Trap Limit',
          //   amount: ['1', '1', '1'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Root Duration',
          //   amount: ['1.6s', '1.8s', '2s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Bonus Attack Speed',
          //   amount: ['40%', '40%', '40%', '40%', '40%'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Bonus Move Speed',
          //   amount: ['1', '1', '1', '1', '1'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Duration',
          //   amount: ['6s', '6s', '6s', '6s', '6s'],
          //   cr: '',
          //   wr: '',
          // },
        ],
      },
    ],
    talents: [
      {
        name: '',
        type: 'Rare',
        color: '#6393F9',
        text: [],
      },
      {
        name: '',
        type: 'Epic',
        color: '#7A02EA',
        text: [],
      },
      {
        name: '',
        type: 'Legendary',
        color: '#FF9000',
        text: [],
      },
    ],
    skins: [
      {
        name: 'Winter War Varya',
        color: '#6393F9',
        type: 'Rare',
        image: 'Varya_WinterWar',
      },
    ],
  },
  {
    name: 'Vox',
    type: ['LANE', 'SNIPER'],
    description: 'Durable berserker who excels in the thick of fights.',
    spotlight: '5Z2KUYPYXEw',
    stats: [
      { name: 'HEALTH', value: '667 - 2054', color: '#4eec8b' },
      { name: 'HEALTH REGEN', value: '3.55 - 7.4', color: '#4eec8b' },
      { name: 'ENERGY', value: '200 - 464', color: '#5bbcff' },
      { name: 'ENERGY REGEN', value: '1.33 - 3.09', color: '#5bbcff' },
      { name: 'WEAPON DAMAGE', value: '54 - 109', color: '#f48596' },
      { name: 'ATTACK SPEED', value: '100% - 136.3%', color: '#f48596' },
      { name: 'ARMOR', value: '25 - 75', color: '#f6ee71' },
      { name: 'SHIELD', value: '20 - 55', color: '#f6ee71' },
      { name: 'ATTACK RANGE', value: '5.6', color: '#e19efb' },
      { name: 'MOVE SPEED', value: '3.4', color: '#e19efb' },
    ],
    model: [{ image: 'Voxblurred' }, { tmodel: 'Vox' }],
    skills: [
      {
        name: "JULIA'S SONG",
        type: 'Perk',
        image: 'Vox-P',
        text: [
          "Vox's abilities mark enemies with Resonance. When basic attacking marked enemies, Resonance Bolts will bounce outwards to two nearby enemies dealing bonus crystal damage while refreshing and spreading the Resonance mark.",
          '• Resonance Crystal damage: 20 (+100% of crystal power)',
          '• Resonance bounces deal 50% damage to minions.',
          '• Basic Attacks deal an additional 20-42 (level 1-12) (+50% of crystal power)',
        ],
        video: 'Vox-P',
        stats: [],
      },
      {
        name: 'SONIC ZOOM',
        type: 'A ABILITY',
        image: 'Vox-A',
        text: [
          'Vox dashes in the targeted direction, throwing two basic attacks to the nearest enemy marked by Resonance (prioritizing heroes).',
        ],
        video: 'Vox-A',
        stats: [
          // {
          //   name: 'Cooldown',
          //   amount: ['8s', '7.5s', '7s', '6.5s', '6s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Energy Cost',
          //   amount: ['25', '30', '35', '40', '45'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Damage',
          //   amount: ['0', '0', '0', '0', '0'],
          //   cr: '',
          //   wr: '100%',
          // },
          // {
          //   name: 'Bonus Damage',
          //   amount: ['80', '120', '160', '200', '240'],
          //   cr: '100%',
          //   wr: '',
          // },
          // {
          //   name: 'Bonus Range',
          //   amount: ['0', '0', '0', '0', '0'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Stun Duration',
          //   amount: ['1s', '1s', '1s', '1s', '1s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Charge Time',
          //   amount: ['1.6s', '1.6s', '1.6s', '1.6s', '1.2s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Duration',
          //   amount: ['6s', '6s', '6s', '6s', '6s'],
          //   cr: '',
          //   wr: '',
          // },
        ],
      },
      {
        name: 'PULSE',
        type: 'B ABILITY',
        image: 'Vox-B',
        text: [
          'Vox emits a sonic pulse that echoes off nearby enemies and applies Resonance. The pulse applies a slow that is significantly stronger near its center.',
          "• Each upgrade to Pulse increases the damage of Vox's bouncing Resonance bolts.",
          '• Overdrive: Resonance bounce range increased by 2.',
        ],
        video: 'Vox-B',
        stats: [
          // {
          //   name: 'Cooldown',
          //   amount: ['10s', '9.5s', '9s', '8.5s', '8s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Energy Cost',
          //   amount: ['25', '30', '35', '40', '45'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Damage',
          //   amount: ['140', '190', '240', '290', '390'],
          //   cr: '175%',
          //   wr: '140%',
          // },
          // {
          //   name: 'Range',
          //   amount: ['5.5', '5.5', '5.5', '5.5', '7.5'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Bonus Move Speed Duration',
          //   amount: ['3s', '3s', '3s', '3s', '3s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Bonus Attack Speed',
          //   amount: ['40%', '40%', '40%', '40%', '40%'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Bonus Move Speed',
          //   amount: ['1', '1', '1', '1', '1'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Duration',
          //   amount: ['6s', '6s', '6s', '6s', '6s'],
          //   cr: '',
          //   wr: '',
          // },
        ],
      },
      {
        name: 'WAIT FOR IT...',
        type: 'ULTIMATE',
        image: 'Vox-C',
        text: [
          'Vox fires an ultrasonic wave that applies Resonance to enemies in its path. Shortly after, a wide shockwave explodes along the same path, dealing crystal damage and silencing enemies.',
          '• Striking enemy heroes with the shockwave will also cause Resonance Bolts to bounce outward to other enemies.',
        ],
        video: 'Vox-C',
        stats: [
          // {
          //   name: 'Cooldown',
          //   amount: ['25s', '20s', '15s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Energy Cost',
          //   amount: ['50', '60', '70'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Damage',
          //   amount: ['300', '450', '600'],
          //   cr: '150%',
          //   wr: '',
          // },
          // {
          //   name: 'Trap Limit',
          //   amount: ['1', '1', '1'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Root Duration',
          //   amount: ['1.6s', '1.8s', '2s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Bonus Attack Speed',
          //   amount: ['40%', '40%', '40%', '40%', '40%'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Bonus Move Speed',
          //   amount: ['1', '1', '1', '1', '1'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Duration',
          //   amount: ['6s', '6s', '6s', '6s', '6s'],
          //   cr: '',
          //   wr: '',
          // },
        ],
      },
    ],
    talents: [
      {
        name: 'Deep Dash',
        type: 'Rare',
        color: '#6393F9',
        text: [
          'Sonic Zoom (A) has 3 increased dash range. Vox passively gains attack speed.',
          '• Passive Attack Speed +25% (+1%)',
          '• Cooldown 125% (-2.5%)',
        ],
      },
      {
        name: 'Sound Barrier',
        type: 'Epic',
        color: '#7A02EA',
        text: [
          'Vox’s basic attacks periodically grant him a health barrier.',
          '• Max Health to Barrier 10% (+3%)',
          '• Barrier Duration 4s',
        ],
      },
      {
        name: 'Echo Chamber',
        type: 'Legendary',
        color: '#FF9000',
        text: [
          'Julia’s Song (Perk) Resonance bolts have an additional bounce.',
          '• Damage 60% (+10%)',
        ],
      },
    ],
    skins: [
      {
        name: 'Sky Captain Vox',
        color: '#6393F9',
        type: 'Rare',
        image: 'Vox_SkyCaptain',
      },
      {
        name: 'Cloud Raider Vox',
        color: '#7A02EA',
        type: 'Epic',
        image: 'Vox_CloudRaider',
      },
      {
        name: 'Evolution Vox',
        color: '#FF9000',
        type: 'Legendary',
        image: 'Vox_Evolution',
      },
      {
        name: 'School Days Vox',
        color: '#7A02EA',
        type: 'Epic',
        image: 'Vox_SchoolDays',
      },
      {
        name: 'Vox On Ice',
        color: '#FF9000',
        type: 'Legendary',
        image: 'Vox_OnIce',
      },
    ],
  },
  {
    name: 'Yates',
    type: ['JUNGLE', 'PROTECTOR'],
    description:
      'Battelfield commander who grabs enemies and has a global presence.',
    spotlight: 'K6kHZW3Vq2g',
    stats: [
      { name: 'HEALTH', value: '857 - 2672', color: '#4eec8b' },
      { name: 'HEALTH REGEN', value: '(+)', color: '#4eec8b' },
      { name: 'ENERGY', value: '174 - 471', color: '#5bbcff' },
      { name: 'ENERGY REGEN', value: '(+)', color: '#5bbcff' },
      { name: 'WEAPON DAMAGE', value: '82 - 172', color: '#f48596' },
      { name: 'ATTACK SPEED', value: '100% - 136.3%', color: '#f48596' },
      { name: 'ARMOR', value: '35 - 100', color: '#f6ee71' },
      { name: 'SHIELD', value: '20 - 75', color: '#f6ee71' },
      { name: 'ATTACK RANGE', value: '3.4', color: '#e19efb' },
      { name: 'MOVE SPEED', value: '3.4', color: '#e19efb' },
    ],
    model: [{ image: 'Yatesblurred' }, { tmodel: 'Yates' }],
    skills: [
      {
        name: 'DEVASTATION FLAIL',
        type: 'Perk',
        image: 'Yates-P',
        text: [
          'Yates can combo up to three basic attacks within a short time of each other for increasingly powerful effects.',
          'Second Hit: Bonus damage and gain a small movespeed boost.',
          'Third Hit: Bonus damage and gain a large movespeed boost.',
        ],
        video: 'Yates-P',
        stats: [],
      },
      {
        name: 'WOLF’S MAW',
        type: 'A ABILITY',
        image: 'Yates-A',
        text: [
          'Yates extends his flail forward, pulling in the first enemy hit.',
        ],
        video: 'Yates-A',
        stats: [
          // {
          //   name: 'Cooldown',
          //   amount: ['8s', '7.5s', '7s', '6.5s', '6s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Energy Cost',
          //   amount: ['25', '30', '35', '40', '45'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Damage',
          //   amount: ['0', '0', '0', '0', '0'],
          //   cr: '',
          //   wr: '100%',
          // },
          // {
          //   name: 'Bonus Damage',
          //   amount: ['80', '120', '160', '200', '240'],
          //   cr: '100%',
          //   wr: '',
          // },
          // {
          //   name: 'Bonus Range',
          //   amount: ['0', '0', '0', '0', '0'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Stun Duration',
          //   amount: ['1s', '1s', '1s', '1s', '1s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Charge Time',
          //   amount: ['1.6s', '1.6s', '1.6s', '1.6s', '1.2s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Duration',
          //   amount: ['6s', '6s', '6s', '6s', '6s'],
          //   cr: '',
          //   wr: '',
          // },
        ],
      },
      {
        name: 'OVERWHELM',
        type: 'B ABILITY',
        image: 'Yates-B',
        text: [
          'Yates gathers energy for 1.5s before releasing a shockwave around himself, stunning affected enemies.',
        ],
        video: 'Yates-B',
        stats: [
          // {
          //   name: 'Cooldown',
          //   amount: ['10s', '9.5s', '9s', '8.5s', '8s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Energy Cost',
          //   amount: ['25', '30', '35', '40', '45'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Damage',
          //   amount: ['140', '190', '240', '290', '390'],
          //   cr: '175%',
          //   wr: '140%',
          // },
          // {
          //   name: 'Range',
          //   amount: ['5.5', '5.5', '5.5', '5.5', '7.5'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Bonus Move Speed Duration',
          //   amount: ['3s', '3s', '3s', '3s', '3s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Bonus Attack Speed',
          //   amount: ['40%', '40%', '40%', '40%', '40%'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Bonus Move Speed',
          //   amount: ['1', '1', '1', '1', '1'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Duration',
          //   amount: ['6s', '6s', '6s', '6s', '6s'],
          //   cr: '',
          //   wr: '',
          // },
        ],
      },
      {
        name: 'IRON MANDATE',
        type: 'ULTIMATE',
        image: 'Yates-C',
        text: [
          'Yates leaps to the chosen location, dealing damage and slowing enemies while granting allies a barrier.',
          'Overwhelm will not disperse until Yates lands.',
          'Note: This is a global ability which means it can be casted anywhere in the map',
        ],
        video: 'Yates-C',
        stats: [
          // {
          //   name: 'Cooldown',
          //   amount: ['25s', '20s', '15s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Energy Cost',
          //   amount: ['50', '60', '70'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Damage',
          //   amount: ['300', '450', '600'],
          //   cr: '150%',
          //   wr: '',
          // },
          // {
          //   name: 'Trap Limit',
          //   amount: ['1', '1', '1'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Root Duration',
          //   amount: ['1.6s', '1.8s', '2s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Bonus Attack Speed',
          //   amount: ['40%', '40%', '40%', '40%', '40%'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Bonus Move Speed',
          //   amount: ['1', '1', '1', '1', '1'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Duration',
          //   amount: ['6s', '6s', '6s', '6s', '6s'],
          //   cr: '',
          //   wr: '',
          // },
        ],
      },
    ],
    talents: [
      {
        name: 'Extended Hooks',
        type: 'Rare',
        color: '#6393F9',
        text: [
          'Wolf’s May (A) has increased range.',
          '• Cooldown 110% (-2%)',
          '• Damage 75% (+5%)',
          '• Bonus Range 2.5 (+0.4)',
        ],
      },
      {
        name: 'Whiplash',
        type: 'Epic',
        color: '#7A02EA',
        text: [
          'Devastation Flail (Perk) third hit deals greatly increased damage.',
          '• Trap Limit 3',
          '• Damage 120%',
          '• Passive Attack Speed +0%',
          '• Bonus Range 6',
        ],
        image: '',
      },
      {
        name: 'Rapid Response',
        type: 'Legendary',
        color: '#FF9000',
        text: [
          'Iron Mandate (Ult) completes much more quickly.',
          '• Cooldown 60%',
          '• Damage 120%',
          '• Barrier 140%',
        ],
        image: '',
      },
    ],
    skins: [
      {
        name: 'Crimson Wolf Yates',
        color: '#6393F9',
        type: 'Rare',
        price: '1200',
        image: 'Yates_CrimsonWolf',
      },
    ],
  },
]
