export const heroTabs = [
  'ALL',
  'ASSASSINS',
  'MAGE',
  'PROTECTOR',
  'SNIPER',
  'WARRIOR',
]

export const heroCards = [
  {
    name: 'Ylva',
    type: ['JUNGLE', 'ASSASSIN'],
    description: 'A huntress that stalks her prey and lays traps for them.',
    spotlight: 'K6kHZW3Vq2g',
    stats: [
      { name: 'HEALTH', value: '703 - 2107', color: '#4eec8b' },
      { name: 'HEALTH REGEN', value: '(+)', color: '#4eec8b' },
      { name: 'ENERGY', value: '203 - 610', color: '#5bbcff' },
      { name: 'ENERGY REGEN', value: '(+)', color: '#5bbcff' },
      { name: 'WEAPON DAMAGE', value: '70 - 125', color: '#f48596' },
      { name: 'ATTACK SPEED', value: '100% - 136.3%', color: '#f48596' },
      { name: 'ARMOR', value: '25 - 75', color: '#f6ee71' },
      { name: 'SHIELD', value: '20 - 55', color: '#f6ee71' },
      { name: 'ATTACK RANGE', value: '5.5', color: '#e19efb' },
      { name: 'MOVE SPEED', value: '3.6', color: '#e19efb' },
    ],
    skills: [
      {
        name: 'Hunter’s Sense',
        type: 'Perk',
        image: 'Ylva-P',
        text: [
          'Ylva can detect the location and movement direction of enemy heroes through walls and brush, as long as they are moving and within her vision range.',
        ],
        video: 'Ylva-P',
        stats: [],
      },
      {
        name: 'Charge Shot',
        type: 'A ABILITY',
        image: 'Ylva-A',
        text: [
          'Ylva charges her weapon, causing her next basic attack to deal bonus damage based on the time spent charging. After it reaches full charge the attack will also stun. While active, Ylva is slowed. Reactivate to cancel.',
          '• Overdrive: At max rank, the time it takes to reach full charge is reduced.',
        ],
        video: 'Ylva-A',
        stats: [
          {
            name: 'Cooldown',
            amount: ['8s', '7.5s', '7s', '6.5s', '6s'],
            cr: '',
            wr: '',
          },
          {
            name: 'Energy Cost',
            amount: ['25', '30', '35', '40', '45'],
            cr: '',
            wr: '',
          },
          {
            name: 'Damage',
            amount: ['0', '0', '0', '0', '0'],
            cr: '',
            wr: '100%',
          },
          {
            name: 'Bonus Damage',
            amount: ['80', '120', '160', '200', '240'],
            cr: '100%',
            wr: '',
          },
          {
            name: 'Bonus Range',
            amount: ['0', '0', '0', '0', '0'],
            cr: '',
            wr: '',
          },
          {
            name: 'Stun Duration',
            amount: ['1s', '1s', '1s', '1s', '1s'],
            cr: '',
            wr: '',
          },
          {
            name: 'Charge Time',
            amount: ['1.6s', '1.6s', '1.6s', '1.6s', '1.2s'],
            cr: '',
            wr: '',
          },
          {
            name: 'Duration',
            amount: ['6s', '6s', '6s', '6s', '6s'],
            cr: '',
            wr: '',
          },
        ],
      },
      {
        name: 'Crimson Fang',
        type: 'B ABILITY',
        image: 'Ylva-B',
        text: [
          'Ylva lunges at her target to deliver a powerful strike that deals more damage to immobilized targets. She then gains additional move and attack speed for a short duration.',
          '• Overdrive: At max rank, lunge range is increased.',
        ],
        video: 'Ylva-B',
        stats: [
          {
            name: 'Cooldown',
            amount: ['10s', '9.5s', '9s', '8.5s', '8s'],
            cr: '',
            wr: '',
          },
          {
            name: 'Energy Cost',
            amount: ['25', '30', '35', '40', '45'],
            cr: '',
            wr: '',
          },
          {
            name: 'Damage',
            amount: ['140', '190', '240', '290', '390'],
            cr: '175%',
            wr: '140%',
          },
          {
            name: 'Range',
            amount: ['5.5', '5.5', '5.5', '5.5', '7.5'],
            cr: '',
            wr: '',
          },
          {
            name: 'Bonus Move Speed Duration',
            amount: ['3s', '3s', '3s', '3s', '3s'],
            cr: '',
            wr: '',
          },
          {
            name: 'Bonus Attack Speed',
            amount: ['40%', '40%', '40%', '40%', '40%'],
            cr: '',
            wr: '',
          },
          {
            name: 'Bonus Move Speed',
            amount: ['1', '1', '1', '1', '1'],
            cr: '',
            wr: '',
          },
          {
            name: 'Duration',
            amount: ['6s', '6s', '6s', '6s', '6s'],
            cr: '',
            wr: '',
          },
        ],
      },
      {
        name: 'VERSE OF JUDGEMENT',
        type: 'ULTIMATE',
        image: 'Ylva-C',
        text: [
          'Ylva places a mine that arms and stealths. When an enemy hero touches it, it will explode after a short delay, causing all enemies within range to take damage and become rooted. Only 1 trap can exist at once.',
          '• Traps expire after a minute. Basic attacks reduce their remaining duration.',
        ],
        video: 'Ylva-C',
        stats: [
          {
            name: 'Cooldown',
            amount: ['25s', '20s', '15s'],
            cr: '',
            wr: '',
          },
          {
            name: 'Energy Cost',
            amount: ['50', '60', '70'],
            cr: '',
            wr: '',
          },
          {
            name: 'Damage',
            amount: ['300', '450', '600'],
            cr: '150%',
            wr: '',
          },
          {
            name: 'Trap Limit',
            amount: ['1', '1', '1'],
            cr: '',
            wr: '',
          },
          {
            name: 'Root Duration',
            amount: ['1.6s', '1.8s', '2s'],
            cr: '',
            wr: '',
          },
          {
            name: 'Bonus Attack Speed',
            amount: ['40%', '40%', '40%', '40%', '40%'],
            cr: '',
            wr: '',
          },
          {
            name: 'Bonus Move Speed',
            amount: ['1', '1', '1', '1', '1'],
            cr: '',
            wr: '',
          },
          {
            name: 'Duration',
            amount: ['6s', '6s', '6s', '6s', '6s'],
            cr: '',
            wr: '',
          },
        ],
      },
    ],
    talents: [
      {
        name: 'SWIFT SHOT',
        type: 'Rare',
        color: '#6393F9',
        text: [
          'Charge Shot (A) reaches full charge faster.',
          '• Charge Time 80%',
          '• Cooldown 100%',
          '• Damage 100%',
        ],
      },
      {
        name: 'MULTY MINE',
        type: 'Epic',
        color: '#7A02EA',
        text: [
          'Ylva may place up to 3 Blinding Mines (Ult).',
          '• Trap Limit 3',
          '• Cooldown 80%',
          '• Damage 75%',
          '• Bonus Range 6',
        ],
        image: '',
      },
      {
        name: 'SHATTERED FANG',
        type: 'Legendary',
        color: '#FF9000',
        text: [
          'Ylva places a Blinding Mine (Ult) at her feet after using Crimson Fang (B). ',
          '• Cooldown 90%',
          '• Damage 100%',
        ],
        image: '',
      },
    ],
    // { name: '', type: '', color: '', image: '' }
    skins: [],
  },
  { name: 'Adagio', type: ['CAPTAIN', 'PROTECTOR'] },
  { name: 'Alpha', type: ['JUNGLE', 'WARRIOR'] },
  { name: 'Anka', type: ['LANE', 'ASSASSIN'] },
  { name: 'Ardan', type: ['CAPTAIN', 'PROTECTOR'] },
  { name: 'Baptiste', type: ['JUNGLE', 'MAGE'] },
  { name: 'Baron', type: ['LANE', 'SNIPER'] },
  { name: 'Blackfeather', type: ['LANE', 'ASSASSIN'] },
  { name: 'Catherine', type: ['CAPTAIN', 'PROTECTOR'] },
  { name: 'Celeste', type: ['LANE', 'MAGE'] },
  { name: 'Churnwalker', type: ['CAPTAIN', 'WARRIOR'] },
  { name: 'Flicker', type: ['CAPTAIN', 'PROTECTOR'] },
  { name: 'Fortress', type: ['CAPTAIN', 'PROTECTOR'] },
  { name: 'Glaive', type: ['JUNGLE', 'WARRIOR'] },
  { name: 'Grace', type: ['CAPTAIN', 'PROTECTOR'] },
  { name: 'Grumpjaw', type: ['JUNGLE', 'WARRIOR'] },
  { name: 'Gwen', type: ['LANE', 'SNIPER'] },
  { name: 'Idris', type: ['JUNGLE', 'ASSASSIN'] },
  { name: 'Inara', type: ['JUNGLE', 'WARRIOR'] },
  { name: 'Joule', type: ['LANE', 'WARRIOR'] },
  { name: 'Kensei', type: ['LANE', 'JUNGLE', 'ASSASSIN'] },
  { name: 'Kestrel', type: ['JUNGLE', 'SNIPER'] },
  { name: 'Kinetic', type: ['LANE', 'MAGE'] },
  { name: 'Koshka', type: ['JUNGLE', 'ASSASSIN'] },
  { name: 'Krul', type: ['JUNGLE', 'WARRIOR'] },
  { name: 'Lance', type: ['CAPTAIN', 'PROTECTOR'] },
  { name: 'Lorelai', type: ['CAPTAIN', 'PROTECTOR'] },
  { name: 'Lyra', type: ['CAPTAIN', 'PROTECTOR'] },
  { name: 'Magnus', type: ['LANE', 'MAGE'] },
  { name: 'Malene', type: ['LANE', 'MAGE'] },
  { name: 'Ozo', type: ['JUNGLE', 'ASSASSIN'] },
  { name: 'Petal', type: ['JUNGLE', 'SNIPER'] },
  { name: 'Phinn', type: ['CAPTAIN', 'PROTECTOR'] },
  { name: 'Reim', type: ['JUNGLE', 'MAGE'] },
  { name: 'Reza', type: ['JUNGLE', 'ASSASSIN'] },
  { name: 'Ringo', type: ['LANE', 'SNIPER'] },
  { name: 'Rona', type: ['JUNGLE', 'WARRIOR'] },
  { name: 'Samuel', type: ['LANE', 'MAGE'] },
  { name: 'SAW', type: ['LANE', 'SNIPER'] },
  { name: 'Silvernail', type: ['LANE', 'SNIPER'] },
  { name: 'Skaarf', type: ['LANE', 'MAGE'] },
  { name: 'Skye', type: ['LANE', 'SNIPER'] },
  { name: 'Taka', type: ['JUNGLE', 'ASSASSIN'] },
  { name: 'Tony', type: ['JUNGLE', 'WARRIOR'] },
  { name: 'Varya', type: ['LANE', 'MAGE'] },
  {
    name: 'Vox',
    type: ['LANE', 'SNIPER'],
    description: 'Durable berserker who excels in the thick of fights.',
    spotlight: '5Z2KUYPYXEw',
    stats: [
      { name: 'HEALTH', value: '667 - 2054', color: '#4eec8b' },
      { name: 'HEALTH REGEN', value: '3.55 - 7.4', color: '#4eec8b' },
      { name: 'ENERGY', value: '200 - 464', color: '#5bbcff' },
      { name: 'ENERGY REGEN', value: '1.33 - 3.09', color: '#5bbcff' },
      { name: 'WEAPON DAMAGE', value: '54 - 109', color: '#f48596' },
      { name: 'ATTACK SPEED', value: '100% - 136.3%', color: '#f48596' },
      { name: 'ARMOR', value: '25 - 75', color: '#f6ee71' },
      { name: 'SHIELD', value: '20 - 55', color: '#f6ee71' },
      { name: 'ATTACK RANGE', value: '5.6', color: '#e19efb' },
      { name: 'MOVE SPEED', value: '3.4', color: '#e19efb' },
    ],
    model: [{ image: 'Voxblurred' }, { tmodel: 'Vox' }],
    skills: [
      {
        name: "JULIA'S SONG",
        type: 'Perk',
        image: 'Vox-P',
        text: [
          "Vox's abilities mark enemies with Resonance. When basic attacking marked enemies, Resonance Bolts will bounce outwards to two nearby enemies dealing bonus crystal damage while refreshing and spreading the Resonance mark.",
          '• Resonance Crystal damage: 20 (+100% of crystal power)',
          '• Resonance bounces deal 50% damage to minions.',
          '• Basic Attacks deal an additional 20-42 (level 1-12) (+50% of crystal power)',
        ],
        video: 'Vox-P',
        stats: [],
      },
      {
        name: 'SONIC ZOOM',
        type: 'A ABILITY',
        image: 'Vox-A',
        text: [
          'Vox dashes in the targeted direction, throwing two basic attacks to the nearest enemy marked by Resonance (prioritizing heroes).',
        ],
        video: 'Vox-A',
        stats: [
          // {
          //   name: 'Cooldown',
          //   amount: ['8s', '7.5s', '7s', '6.5s', '6s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Energy Cost',
          //   amount: ['25', '30', '35', '40', '45'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Damage',
          //   amount: ['0', '0', '0', '0', '0'],
          //   cr: '',
          //   wr: '100%',
          // },
          // {
          //   name: 'Bonus Damage',
          //   amount: ['80', '120', '160', '200', '240'],
          //   cr: '100%',
          //   wr: '',
          // },
          // {
          //   name: 'Bonus Range',
          //   amount: ['0', '0', '0', '0', '0'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Stun Duration',
          //   amount: ['1s', '1s', '1s', '1s', '1s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Charge Time',
          //   amount: ['1.6s', '1.6s', '1.6s', '1.6s', '1.2s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Duration',
          //   amount: ['6s', '6s', '6s', '6s', '6s'],
          //   cr: '',
          //   wr: '',
          // },
        ],
      },
      {
        name: 'PULSE',
        type: 'B ABILITY',
        image: 'Vox-B',
        text: [
          'Vox emits a sonic pulse that echoes off nearby enemies and applies Resonance. The pulse applies a slow that is significantly stronger near its center.',
          "• Each upgrade to Pulse increases the damage of Vox's bouncing Resonance bolts.",
          '• Overdrive: Resonance bounce range increased by 2.',
        ],
        video: 'Vox-B',
        stats: [
          // {
          //   name: 'Cooldown',
          //   amount: ['10s', '9.5s', '9s', '8.5s', '8s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Energy Cost',
          //   amount: ['25', '30', '35', '40', '45'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Damage',
          //   amount: ['140', '190', '240', '290', '390'],
          //   cr: '175%',
          //   wr: '140%',
          // },
          // {
          //   name: 'Range',
          //   amount: ['5.5', '5.5', '5.5', '5.5', '7.5'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Bonus Move Speed Duration',
          //   amount: ['3s', '3s', '3s', '3s', '3s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Bonus Attack Speed',
          //   amount: ['40%', '40%', '40%', '40%', '40%'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Bonus Move Speed',
          //   amount: ['1', '1', '1', '1', '1'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Duration',
          //   amount: ['6s', '6s', '6s', '6s', '6s'],
          //   cr: '',
          //   wr: '',
          // },
        ],
      },
      {
        name: 'WAIT FOR IT...',
        type: 'ULTIMATE',
        image: 'Vox-C',
        text: [
          'Vox fires an ultrasonic wave that applies Resonance to enemies in its path. Shortly after, a wide shockwave explodes along the same path, dealing crystal damage and silencing enemies.',
          '• Striking enemy heroes with the shockwave will also cause Resonance Bolts to bounce outward to other enemies.',
        ],
        video: 'Vox-C',
        stats: [
          // {
          //   name: 'Cooldown',
          //   amount: ['25s', '20s', '15s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Energy Cost',
          //   amount: ['50', '60', '70'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Damage',
          //   amount: ['300', '450', '600'],
          //   cr: '150%',
          //   wr: '',
          // },
          // {
          //   name: 'Trap Limit',
          //   amount: ['1', '1', '1'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Root Duration',
          //   amount: ['1.6s', '1.8s', '2s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Bonus Attack Speed',
          //   amount: ['40%', '40%', '40%', '40%', '40%'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Bonus Move Speed',
          //   amount: ['1', '1', '1', '1', '1'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Duration',
          //   amount: ['6s', '6s', '6s', '6s', '6s'],
          //   cr: '',
          //   wr: '',
          // },
        ],
      },
    ],
    talents: [
      {
        name: 'Deep Dash',
        type: 'Rare',
        color: '#6393F9',
        text: [
          'Sonic Zoom (A) has 3 increased dash range. Vox passively gains attack speed.',
          '• Passive Attack Speed +25% (+1%)',
          '• Cooldown 125% (-2.5%)',
        ],
      },
      {
        name: 'Sound Barrier',
        type: 'Epic',
        color: '#7A02EA',
        text: [
          'Vox’s basic attacks periodically grant him a health barrier.',
          '• Max Health to Barrier 10% (+3%)',
          '• Barrier Duration 4s',
        ],
      },
      {
        name: 'Echo Chamber',
        type: 'Legendary',
        color: '#FF9000',
        text: [
          'Julia’s Song (Perk) Resonance bolts have an additional bounce.',
          '• Damage 60% (+10%)',
        ],
      },
    ],
    skins: [
      {
        name: 'Sky Captain Vox',
        color: '#6393F9',
        type: 'Rare',
        image: 'Vox_SkyCaptain',
      },
      {
        name: 'Cloud Raider Vox',
        color: '#7A02EA',
        type: 'Epic',
        image: 'Vox_CloudRaider',
      },
      {
        name: 'Evolution Vox',
        color: '#FF9000',
        type: 'Legendary',
        image: 'Vox_Evolution',
      },
      {
        name: 'School Days Vox',
        color: '#7A02EA',
        type: 'Epic',
        image: 'Vox_SchoolDays',
      },
      {
        name: 'Vox On Ice',
        color: '#FF9000',
        type: 'Legendary',
        image: 'Vox_OnIce',
      },
    ],
  },
  {
    name: 'Yates',
    type: ['JUNGLE', 'PROTECTOR'],
    description:
      'Battelfield commander who grabs enemies and has a global presence.',
    spotlight: 'K6kHZW3Vq2g',
    stats: [
      { name: 'HEALTH', value: '857 - 2672', color: '#4eec8b' },
      { name: 'HEALTH REGEN', value: '(+)', color: '#4eec8b' },
      { name: 'ENERGY', value: '174 - 471', color: '#5bbcff' },
      { name: 'ENERGY REGEN', value: '(+)', color: '#5bbcff' },
      { name: 'WEAPON DAMAGE', value: '82 - 172', color: '#f48596' },
      { name: 'ATTACK SPEED', value: '100% - 136.3%', color: '#f48596' },
      { name: 'ARMOR', value: '35 - 100', color: '#f6ee71' },
      { name: 'SHIELD', value: '20 - 75', color: '#f6ee71' },
      { name: 'ATTACK RANGE', value: '3.4', color: '#e19efb' },
      { name: 'MOVE SPEED', value: '3.4', color: '#e19efb' },
    ],
    model: [{ image: 'Yatesblurred' }, { tmodel: 'Yates' }],
    skills: [
      {
        name: 'DEVASTATION FLAIL',
        type: 'Perk',
        image: 'Yates-P',
        text: [
          'Yates can combo up to three basic attacks within a short time of each other for increasingly powerful effects.',
          'Second Hit: Bonus damage and gain a small movespeed boost.',
          'Third Hit: Bonus damage and gain a large movespeed boost.',
        ],
        video: 'Yates-P',
        stats: [],
      },
      {
        name: 'WOLF’S MAW',
        type: 'A ABILITY',
        image: 'Yates-A',
        text: [
          'Yates extends his flail forward, pulling in the first enemy hit.',
        ],
        video: 'Yates-A',
        stats: [
          // {
          //   name: 'Cooldown',
          //   amount: ['8s', '7.5s', '7s', '6.5s', '6s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Energy Cost',
          //   amount: ['25', '30', '35', '40', '45'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Damage',
          //   amount: ['0', '0', '0', '0', '0'],
          //   cr: '',
          //   wr: '100%',
          // },
          // {
          //   name: 'Bonus Damage',
          //   amount: ['80', '120', '160', '200', '240'],
          //   cr: '100%',
          //   wr: '',
          // },
          // {
          //   name: 'Bonus Range',
          //   amount: ['0', '0', '0', '0', '0'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Stun Duration',
          //   amount: ['1s', '1s', '1s', '1s', '1s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Charge Time',
          //   amount: ['1.6s', '1.6s', '1.6s', '1.6s', '1.2s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Duration',
          //   amount: ['6s', '6s', '6s', '6s', '6s'],
          //   cr: '',
          //   wr: '',
          // },
        ],
      },
      {
        name: 'OVERWHELM',
        type: 'B ABILITY',
        image: 'Yates-B',
        text: [
          'Yates gathers energy for 1.5s before releasing a shockwave around himself, stunning affected enemies.',
        ],
        video: 'Yates-B',
        stats: [
          // {
          //   name: 'Cooldown',
          //   amount: ['10s', '9.5s', '9s', '8.5s', '8s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Energy Cost',
          //   amount: ['25', '30', '35', '40', '45'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Damage',
          //   amount: ['140', '190', '240', '290', '390'],
          //   cr: '175%',
          //   wr: '140%',
          // },
          // {
          //   name: 'Range',
          //   amount: ['5.5', '5.5', '5.5', '5.5', '7.5'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Bonus Move Speed Duration',
          //   amount: ['3s', '3s', '3s', '3s', '3s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Bonus Attack Speed',
          //   amount: ['40%', '40%', '40%', '40%', '40%'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Bonus Move Speed',
          //   amount: ['1', '1', '1', '1', '1'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Duration',
          //   amount: ['6s', '6s', '6s', '6s', '6s'],
          //   cr: '',
          //   wr: '',
          // },
        ],
      },
      {
        name: 'IRON MANDATE',
        type: 'ULTIMATE',
        image: 'Yates-C',
        text: [
          'Yates leaps to the chosen location, dealing damage and slowing enemies while granting allies a barrier.',
          'Overwhelm will not disperse until Yates lands.',
          'Note: This is a global ability which means it can be casted anywhere in the map',
        ],
        video: 'Yates-C',
        stats: [
          // {
          //   name: 'Cooldown',
          //   amount: ['25s', '20s', '15s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Energy Cost',
          //   amount: ['50', '60', '70'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Damage',
          //   amount: ['300', '450', '600'],
          //   cr: '150%',
          //   wr: '',
          // },
          // {
          //   name: 'Trap Limit',
          //   amount: ['1', '1', '1'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Root Duration',
          //   amount: ['1.6s', '1.8s', '2s'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Bonus Attack Speed',
          //   amount: ['40%', '40%', '40%', '40%', '40%'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Bonus Move Speed',
          //   amount: ['1', '1', '1', '1', '1'],
          //   cr: '',
          //   wr: '',
          // },
          // {
          //   name: 'Duration',
          //   amount: ['6s', '6s', '6s', '6s', '6s'],
          //   cr: '',
          //   wr: '',
          // },
        ],
      },
    ],
    talents: [
      {
        name: 'Extended Hooks',
        type: 'Rare',
        color: '#6393F9',
        text: [
          'Wolf’s May (A) has increased range.',
          '• Cooldown 110% (-2%)',
          '• Damage 75% (+5%)',
          '• Bonus Range 2.5 (+0.4)',
        ],
      },
      {
        name: 'Whiplash',
        type: 'Epic',
        color: '#7A02EA',
        text: [
          'Devastation Flail (Perk) third hit deals greatly increased damage.',
          '• Trap Limit 3',
          '• Damage 120%',
          '• Passive Attack Speed +0%',
          '• Bonus Range 6',
        ],
        image: '',
      },
      {
        name: 'Rapid Response',
        type: 'Legendary',
        color: '#FF9000',
        text: [
          'Iron Mandate (Ult) completes much more quickly.',
          '• Cooldown 60%',
          '• Damage 120%',
          '• Barrier 140%',
        ],
        image: '',
      },
    ],
    skins: [
      {
        name: 'Crimson Wolf Yates',
        color: '#6393F9',
        type: 'Rare',
        price: '1200',
        image: 'Yates_CrimsonWolf',
      },
    ],
  },
]
