export const frontmatter = {
  name: 'Baron',
  type: ['LANE', 'SNIPER'],
  role: ['LANE'],
  path: '/Baron',
  description: 'Rocket soldier who can nuke anywhere on the map.',
  spotlight: 'qTHw50-xTbc',
  stats: [
    { name: 'HEALTH', value: '679 - 2054', color: '#4eec8b' },
    { name: 'HEALTH REGEN', value: '3.29 - 7.91', color: '#4eec8b' },
    { name: 'ENERGY', value: '270 - 765', color: '#5bbcff' },
    { name: 'ENERGY REGEN', value: '6.67 - 18', color: '#5bbcff' },
    { name: 'WEAPON DAMAGE', value: '71 - 130', color: '#f48596' },
    { name: 'ATTACK SPEED', value: '100% - 111%', color: '#f48596' },
    { name: 'ARMOR', value: '25 - 75', color: '#f6ee71' },
    { name: 'SHIELD', value: '20 - 55', color: '#f6ee71' },
    { name: 'ATTACK RANGE', value: '5.4', color: '#e19efb' },
    { name: 'MOVE SPEED', value: '3', color: '#e19efb' },
  ],
  model: [{ image: 'Baronblurred' }, { tmodel: 'Baron' }],
  skills: [
    {
      name: 'ROCKET LAUNCHER',
      type: 'Perk',
      image: 'Baron-P',
      text: [
        'Baron’s basic attacks deal 125% weapon damage to the target and surrounding enemies.',
        '• Explosions deal 90% damage to surrounding enemies.',
        '• Explosions less damage to minions.',
      ],
    },
    {
      name: 'PORCUPINE MORTAR',
      type: 'A ABILITY',
      text: [
        'Baron launches artillery toward the target location, heavily damaging enemies on impact. This ability has 2 charges.',
        '• Enemies are also slowed by 10% (+10% weapon power), decaying over 2.2s.',
        '• This slow is further increased with weapon power up to a cap of 30% with 200 weapon power.',
        '• The range of this ability increases with crystal power up to a cap of 11 meters with 200 crystal power.',
        '• Baron can fire this while using Jump Jets.',
        '• Deals less damage to minions.',
      ],
      image: 'Baron-A',
      stats: [
        {
          name: 'Charge Time',
          amount: ['5s', '4.5s', '4s', '3.5s', '2.5s'],
          cr: '',
          wr: '',
        },
        {
          name: 'Energy Cost',
          amount: ['40', '50', '60', '70', '80'],
          cr: '',
          wr: '',
        },
        {
          name: 'Damege',
          amount: ['40', '120', '200', '280', '360'],
          cr: '130%',
          wr: '70%',
        },
        {
          name: 'Range',
          amount: ['8', '8', '8', '8', '8'],
          cr: '1.5%',
          wr: '',
        },
      ],
    },
    {
      name: 'JUMP JETS',
      type: 'B ABILITY',
      image: 'Baron-B',
      text: [
        'After a brief delay, Baron jets to the location then gains bonus move speed for 2.1s. His next basic attack is a double shot.',
        '• Overdrive: At max rank, Baron ignores all debuffs while leaping.',
        '• Baron takes longer to power up the farther away he is from his destination.However, this delay is reduced by weapon and crystal power up to a maximum of 200 total.',
        "• Basic attacks reduce this ability's cooldown by 10%.",
      ],
      stats: [
        {
          name: 'Cooldown',
          amount: ['20s', '19s', '18s', '17s', '14s'],
          cr: '',
          wr: '',
        },
        {
          name: 'Energy Cost',
          amount: ['130', '140', '150', '160', '170'],
          cr: '',
          wr: '',
        },
        {
          name: 'Speed Boost',
          amount: ['0.5', '0.6', '0.7', '0.8', '1'],
          cr: '',
          wr: '0.3%',
        },
      ],
    },
    {
      name: 'ION CANNON',
      type: 'ULTIMATE',
      image: 'Baron-C',
      text: [
        'Baron targets a location anywhere on the map for an orbital strike., obliterating the area after a 3s delay.',
        '• Deals 50 % less damage to minions.',
        '• This deals full damage to enemies near the center, falling off to 65 % damage at the edges.',
        '• Although Baron and his allies see the designated location immediately, enemies only become aware of it 0.9s before impact.',
        "• Passive: Each rank of this ability permanently increases Baron's basic-attac range.",
        '• Deals less damage to minions.',
      ],
      stats: [
        {
          name: 'Cooldown',
          amount: ['80s', '70s', '60s'],
          cr: '',
          wr: '',
        },
        {
          name: 'Energy Cost',
          amount: ['100', '125', '150'],
          cr: '',
          wr: '',
        },
        {
          name: 'Damege at Center',
          amount: ['500', '750', '1000'],
          cr: '150%',
          wr: '120%',
        },
        {
          name: 'Bonus Attack Range',
          amount: ['0.4', '0.8', '1.2'],
          cr: '',
          wr: '',
        },
      ],
    },
  ],
  talents: [
    {
      name: 'Turbo Jets',
      type: 'Rare',
      color: '#6393F9',
      text: [
        'Jump Jets (B) has no startup delay and fires three rockets on Baron’s next basic attack.',
        '• Cooldown 110% (-2%)',
        '• Triple Shot Damage 70% (+2%)',
      ],
      image: 'Baron_Rare',
    },
    {
      name: 'Endless Mortars',
      type: 'Epic',
      color: '#7A02EA',
      text: [
        'Porcupine Mortar (A) has 6 additional charges and travels faster.',
        '• Damage 50% (+7.5%)',
        '• Energy Cost 20%',
      ],
      image: 'Baron_Epic',
    },
    {
      name: 'Trion Cannon',
      type: 'Legendary',
      color: '#FF9000',
      text: [
        'Ion Cannon (Ult) has 2 additional charges. Baron passively gains attack range.',
        '• Charge Time 60%',
        '• Damage 80%',
        '• Passive Bonus Attack Range 0.5',
      ],
      image: 'Baron_Legendary',
    },
  ],
  skins: [
    {
      color: '#6393F9',
      name: 'Elite Force Baron',
      type: 'Rare',
      image: 'Baron_Elite_Force_R',
    },
    {
      color: '#FF9000',
      name: 'Fly or Die Baron',
      type: 'Legendary',
      image: 'Baron_Fly_or_Die_Legendary',
    },
  ],
}
