export const frontmatter = {
  name: 'Ozo',
  type: ['JUNGLE', 'ASSASSIN'],
  role: ['JUNGLE'],
  path: '/Ozo',
  description: 'Acrobatic monkey with immense self-healing.',
  spotlight: 'Dp7MIjNuZXc',
  stats: [
    { name: 'HEALTH', value: '769 - 2536', color: '#4eec8b' },
    { name: 'H. REGEN', value: ' - ', color: '#4eec8b' },
    { name: 'ENERGY', value: '350 - 650', color: '#5bbcff' },
    { name: 'ENG REGEN', value: ' - ', color: '#5bbcff' },
    { name: 'WP DAMAGE', value: '80 - 157', color: '#f48596' },
    { name: 'ATK SPD', value: '100% - 136.3%', color: '#f48596' },
    { name: 'ARMOR', value: '30 - 85', color: '#f6ee71' },
    { name: 'SHIELD', value: '20 - 60', color: '#f6ee71' },
    { name: 'ATK RANGE', value: '1.7', color: '#e19efb' },
    { name: 'MOVE SPD', value: '4.0', color: '#e19efb' },
  ],
  model: [{ image: 'Ozoblurred' }, { tmodel: 'Ozo' }],
  skills: [
    {
      name: 'CARNIE LUCK',
      type: 'Perk',
      image: 'Ozo-P',
      text: [
        'Ozo receives 15%-30% additional healing, barrier and fortified health from all sources.',
        '• This does not affect health regeneration.',
      ],
    },
    {
      name: 'THREE-RING CIRCUS',
      type: 'A ABILITY',
      image: 'Ozo-A',
      text: [
        'Ozo can use this ability three times in a 5s window:',
        '• First hit: Smashes the target and other enemies in front of him.',
        '• Second hit: Dashes through his target and deals damage.',
        '• Final hit: Spins and damages all nearby enemies.',
        '• Each hit deals weapon damage, can crit, and triggers basic-attack effects on the primary targer.',
        '• Ozo heals for each enemy damaged by any of these hits (30% against non-heroes).',
      ],
      stats: [
        {
          name: 'Cooldown',
          amount: ['8s', '7.5s', '7s', '6.5s', '5s'],
          cr: ' ',
          wr: ' ',
        },
        {
          name: 'Energy Cost',
          amount: ['50', '55', '60', '65', '75'],
          cr: ' ',
          wr: ' ',
        },
        {
          name: 'First Hit Damage',
          amount: ['15', '25', '35', '45', '55'],
          cr: '75%',
          wr: '100%',
        },
        {
          name: 'Second Hit Damage',
          amount: ['15', '25', '35', '45', '55'],
          cr: '75%',
          wr: '100%',
        },
        {
          name: 'Third Hit Damage',
          amount: ['15', '25', '35', '45', '55'],
          cr: '75%',
          wr: '100%',
        },
        {
          name: 'Healing vs. Heroes',
          amount: ['20', '40', '60', '80', '100'],
          cr: '15%',
          wr: ' ',
        },
      ],
    },
    {
      name: 'ACROBOUNCE',
      type: 'B ABILITY',
      image: 'Ozo-B',
      text: [
        'Ozo jumps onto a target, damaging and slowing it if it is an enemy. While airborne, quickly tap another target to bounce to it. Three hops maximum.',
        '• Each time Ozo starts a jump, he is granted fortified health.',
        '• The final landing deals increased damage plus a bonus per prior bounce.',
        "• If Ozo hops at least twice, he'll get a burst of move speed up to a maximum of 4.5s.",
        '• Deals 50% less damage to minions.',
      ],
      stats: [
        {
          name: 'Cooldown',
          amount: ['10s', '9.5s', '9s', '8.5s', '7s'],
          cr: ' ',
          wr: ' ',
        },
        {
          name: 'Energy Cost',
          amount: ['100', '100', '100', '100', '100'],
          cr: ' ',
          wr: ' ',
        },
        {
          name: 'Damage',
          amount: ['60', '120', '180', '240', '300'],
          cr: '70%',
          wr: ' ',
        },
        {
          name: 'Final Damage',
          amount: ['80', '160', '240', '320', '400'],
          cr: '70%',
          wr: ' ',
        },
        {
          name: 'Bonus Damage/Bounce',
          amount: ['20', '40', '60', '80', '100'],
          cr: '35%',
          wr: ' ',
        },
        {
          name: 'Speed Boost',
          amount: ['3', '3', '3', '3', '3'],
          cr: ' ',
          wr: '0.75%',
        },
        {
          name: 'Bonus Speed Duration',
          amount: ['3', '3', '3', '3', '3'],
          cr: ' ',
          wr: '0.75%',
        },
        {
          name: 'Fortified Health	',
          amount: ['25', '50', '75', '100', '125'],
          cr: '15%',
          wr: ' ',
        },
      ],
    },
    {
      name: 'BANGARANG',
      type: 'ULTIMATE',
      image: 'Ozo-C',
      text: [
        'Ozo charges up, then rolls toward a targeted enemy hero. Upon arrival, Ozo damages, stuns for 0.8s, and flips the target over him.',
        '• While tumbling, Ozo will damage and knock aside other enemies along his path.',
        '• Max travel duration of 1s.',
      ],
      stats: [
        {
          name: 'Cooldown',
          amount: ['70s', '50s', '30s'],
          cr: ' ',
          wr: ' ',
        },
        {
          name: 'Energy Cost',
          amount: ['120', '120', '120'],
          cr: ' ',
          wr: ' ',
        },
        {
          name: 'Primary Target Damage',
          amount: ['250', '400', '550'],
          cr: '150%',
          wr: ' ',
        },
        {
          name: 'Secondary Target Damage',
          amount: ['125', '200', '275'],
          cr: '75%',
          wr: ' ',
        },
      ],
    },
  ],
  talents: [
    {
      name: 'Second Wind',
      type: 'Rare',
      color: '#6393F9',
      text: [
        'Acrobounce (B) is reset upon the third bounce.',
        '• Damage 65% (+2%)',
        '• Fortified Health 155% (+7.5%)',
      ],
      image: 'Talents/Ozo_Rare',
    },
    {
      name: 'Ring Leader',
      type: 'Epic',
      color: '#c78cff',
      text: [
        'Three-Ring Circus (A) heals nearby allies.',
        '• Heal 110% (+7.5%)',
      ],
      image: 'Talents/Ozo_Epic',
    },
    {
      name: 'Bangaranarang!',
      type: 'Legendary',
      color: '#FF9000',
      text: [
        'Bangarang (ult) has 1 additional charge.',
        '• Damage 90% (+15%)',
        '• Cooldown 70% (-7.5%)',
      ],
      image: 'Talents/Ozo_Legendary',
    },
  ],
  skins: [
    {
      color: '#6393F9',
      name: 'Wuxia Ozo',
      type: 'Rare',
      image: 'Ozo_Wuxia_R',
    },
    {
      color: '#c78cff',
      name: 'Winged Ozo',
      type: 'Epic',
      image: 'Winged_Ozo',
    },
    {
      color: '#c78cff',
      name: 'Infernozo',
      type: 'Epic',
      image: 'Ozo_Infernozo',
    },
  ],
}
