export default {
  name: 'Varya',
  type: ['LANE', 'MAGE'],
  description:
    'Shocking valkyrie who chains massive damage across enemy teams.',
  spotlight: 'dMBPEcWHgek',
  stats: [
    { name: 'HEALTH', value: '642 - 2127', color: '#4eec8b' },
    { name: 'HEALTH REGEN', value: '2.81 - 6.22', color: '#4eec8b' },
    { name: 'ENERGY', value: '950 - 1500', color: '#5bbcff' },
    { name: 'ENERGY REGEN', value: '36 - 64.6', color: '#5bbcff' },
    { name: 'WEAPON DAMAGE', value: '-', color: '#f48596' },
    { name: 'ATTACK SPEED', value: '100% - 115%', color: '#f48596' },
    { name: 'ARMOR', value: '25 - 75', color: '#f6ee71' },
    { name: 'SHIELD', value: '20 - 55', color: '#f6ee71' },
    { name: 'ATTACK RANGE', value: '6.2', color: '#e19efb' },
    { name: 'MOVE SPEED', value: '3.2', color: '#e19efb' },
  ],
  model: [{ image: 'Varyablurred' }, { tmodel: 'Varya' }],
  skills: [
    {
      name: 'CHAIN LIGHTNING',
      type: 'Perk',
      image: 'Varya-P',
      text: [
        "Varya's attacks deal 70-114 (level 1-12) (+25% Crystal Power) crystal damage. If Varya holds her ground after attacking, she will consume 170 energy to striker her target again and Chain Lightning up to 3 additional targets.",
        '• Chain Lightning: Deals 37-125 (level 1-12) (+50% Crystal Power) damage to each target.',
      ],
      video: 'Varya-P',
      stats: [],
    },
    {
      name: 'STORMFORGED SPEAR',
      type: 'A ABILITY',
      image: 'Varya-A',
      text: [
        'Varya throws a spear at lightning speed, striking the first enemy in its path. This deals a burst of damage to the target and chains additional damage to nearby targets.',
        '• When cast during or after Arc Recursion, the spear is thrown more quickly.',
        '• Number or additional targets hit is equal to her Chain Lighting attack.',
        '• The initial spear does not impact on lane minions.',
      ],
      video: 'Varya-A',
      stats: [
        // {
        //   name: 'Cooldown',
        //   amount: ['8s', '7.5s', '7s', '6.5s', '6s'],
        //   cr: '',
        //   wr: '',
        // },
        // {
        //   name: 'Energy Cost',
        //   amount: ['25', '30', '35', '40', '45'],
        //   cr: '',
        //   wr: '',
        // },
        // {
        //   name: 'Damage',
        //   amount: ['0', '0', '0', '0', '0'],
        //   cr: '',
        //   wr: '100%',
        // },
        // {
        //   name: 'Bonus Damage',
        //   amount: ['80', '120', '160', '200', '240'],
        //   cr: '100%',
        //   wr: '',
        // },
        // {
        //   name: 'Bonus Range',
        //   amount: ['0', '0', '0', '0', '0'],
        //   cr: '',
        //   wr: '',
        // },
        // {
        //   name: 'Stun Duration',
        //   amount: ['1s', '1s', '1s', '1s', '1s'],
        //   cr: '',
        //   wr: '',
        // },
        // {
        //   name: 'Charge Time',
        //   amount: ['1.6s', '1.6s', '1.6s', '1.6s', '1.2s'],
        //   cr: '',
        //   wr: '',
        // },
        // {
        //   name: 'Duration',
        //   amount: ['6s', '6s', '6s', '6s', '6s'],
        //   cr: '',
        //   wr: '',
        // },
      ],
    },
    {
      name: 'ARC RECURSION',
      type: 'B ABILITY',
      image: 'Varya-B',
      text: [
        'After gathering power for 0.9s, Varya’s next two move commands will instantly dash in the chosen direction, striking the 3 nearest enemies at the end of each dash. For each enemy struck, Varya recovers 5% of her energy and gains a barrier equal to 3% of her health (bonuses doubled on heroes).',
        '• Overdrive: Varya moves further with each dash.',
        '• Varya can dash at any time, but will only dash once if she has not fully charged.',
        '• Varya can activate Stormforged Spear at any time during this ability. Any remaining dashes will trigger after the spear is thrown.',
        '• Deals 50% less damage to minions.',
      ],
      video: 'Varya-B',
      stats: [
        // {
        //   name: 'Cooldown',
        //   amount: ['10s', '9.5s', '9s', '8.5s', '8s'],
        //   cr: '',
        //   wr: '',
        // },
        // {
        //   name: 'Energy Cost',
        //   amount: ['25', '30', '35', '40', '45'],
        //   cr: '',
        //   wr: '',
        // },
        // {
        //   name: 'Damage',
        //   amount: ['140', '190', '240', '290', '390'],
        //   cr: '175%',
        //   wr: '140%',
        // },
        // {
        //   name: 'Range',
        //   amount: ['5.5', '5.5', '5.5', '5.5', '7.5'],
        //   cr: '',
        //   wr: '',
        // },
        // {
        //   name: 'Bonus Move Speed Duration',
        //   amount: ['3s', '3s', '3s', '3s', '3s'],
        //   cr: '',
        //   wr: '',
        // },
        // {
        //   name: 'Bonus Attack Speed',
        //   amount: ['40%', '40%', '40%', '40%', '40%'],
        //   cr: '',
        //   wr: '',
        // },
        // {
        //   name: 'Bonus Move Speed',
        //   amount: ['1', '1', '1', '1', '1'],
        //   cr: '',
        //   wr: '',
        // },
        // {
        //   name: 'Duration',
        //   amount: ['6s', '6s', '6s', '6s', '6s'],
        //   cr: '',
        //   wr: '',
        // },
      ],
    },
    {
      name: "ANVIL'S HAMMER",
      type: 'ULTIMATE',
      image: 'Varya-C',
      text: [
        'After channeling for 2.4s, Varya unleashes the fury of the storm, calling a series of lightning strikes on every enemy hero, regardless of distance. Passively, each rank of the ultimate permanently increases her attack speed and the number enemies her Chain Lightning and Stormforged Spear will hit.',
        '• Lightning strikes target the ground beneath enemy heroes, giving them an opportunity to move out of the way.',
        '• Lightning strikes deal 50% reduced damage to enemies already hit lightning in the same wave.',
        '• Varya can break out of channeling early by activating Stormforged Spear or Arc Recursion. This does not cancel the spell.',
        '• Deals 50% less damage to minions.',
      ],
      video: 'Varya-C',
      stats: [
        // {
        //   name: 'Cooldown',
        //   amount: ['25s', '20s', '15s'],
        //   cr: '',
        //   wr: '',
        // },
        // {
        //   name: 'Energy Cost',
        //   amount: ['50', '60', '70'],
        //   cr: '',
        //   wr: '',
        // },
        // {
        //   name: 'Damage',
        //   amount: ['300', '450', '600'],
        //   cr: '150%',
        //   wr: '',
        // },
        // {
        //   name: 'Trap Limit',
        //   amount: ['1', '1', '1'],
        //   cr: '',
        //   wr: '',
        // },
        // {
        //   name: 'Root Duration',
        //   amount: ['1.6s', '1.8s', '2s'],
        //   cr: '',
        //   wr: '',
        // },
        // {
        //   name: 'Bonus Attack Speed',
        //   amount: ['40%', '40%', '40%', '40%', '40%'],
        //   cr: '',
        //   wr: '',
        // },
        // {
        //   name: 'Bonus Move Speed',
        //   amount: ['1', '1', '1', '1', '1'],
        //   cr: '',
        //   wr: '',
        // },
        // {
        //   name: 'Duration',
        //   amount: ['6s', '6s', '6s', '6s', '6s'],
        //   cr: '',
        //   wr: '',
        // },
      ],
    },
  ],
  talents: [
    {
      name: '',
      type: 'Rare',
      color: '#6393F9',
      text: [],
    },
    {
      name: '',
      type: 'Epic',
      color: '#7A02EA',
      text: [],
    },
    {
      name: '',
      type: 'Legendary',
      color: '#FF9000',
      text: [],
    },
  ],
  skins: [
    {
      name: 'Winter War Varya',
      color: '#6393F9',
      type: 'Rare',
      image: 'Varya_WinterWar',
    },
  ],
}
