export default {
  name: 'Yates',
  type: ['CAPTAIN', 'PROTECTOR'],
  role: ['CAPTAIN'],
  description:
    'Battelfield commander who grabs enemies and has a global presence.',
  spotlight: 'K6kHZW3Vq2g',
  stats: [
    { name: 'HEALTH', value: '857 - 2672', color: '#4eec8b' },
    { name: 'HEALTH REGEN', value: '(+)', color: '#4eec8b' },
    { name: 'ENERGY', value: '174 - 471', color: '#5bbcff' },
    { name: 'ENERGY REGEN', value: '(+)', color: '#5bbcff' },
    { name: 'WEAPON DAMAGE', value: '82 - 172', color: '#f48596' },
    { name: 'ATTACK SPEED', value: '100% - 136.3%', color: '#f48596' },
    { name: 'ARMOR', value: '35 - 100', color: '#f6ee71' },
    { name: 'SHIELD', value: '20 - 75', color: '#f6ee71' },
    { name: 'ATTACK RANGE', value: '3.4', color: '#e19efb' },
    { name: 'MOVE SPEED', value: '3.4', color: '#e19efb' },
  ],
  model: [{ image: 'Yatesblurred' }, { tmodel: 'Yates' }],
  skills: [
    {
      name: 'DEVASTATION FLAIL',
      type: 'Perk',
      image: 'Yates-P',
      text: [
        'Yates can combo up to three basic attacks within a short time of each other for increasingly powerful effects.',
        'Second Hit: Bonus damage and gain a small movespeed boost.',
        'Third Hit: Bonus damage and gain a large movespeed boost.',
      ],
      video: 'Yates-A',
      stats: [],
    },
    {
      name: 'WOLF’S MAW',
      type: 'A ABILITY',
      image: 'Yates-A',
      text: [
        'Yates extends his flail forward, pulling in the first enemy hit.',
      ],
      video: 'Yates-A',
      stats: [
        {
          name: 'Cooldown',
          amount: ['8s', '7.5s', '7s', '6.5s', '6s'],
          cr: '',
          wr: '',
        },
        {
          name: 'Energy Cost',
          amount: ['25', '30', '35', '40', '45'],
          cr: '',
          wr: '',
        },
        {
          name: 'Damage',
          amount: ['0', '0', '0', '0', '0'],
          cr: '',
          wr: '100%',
        },
        {
          name: 'Bonus Damage',
          amount: ['80', '120', '160', '200', '240'],
          cr: '100%',
          wr: '',
        },
        {
          name: 'Bonus Range',
          amount: ['0', '0', '0', '0', '0'],
          cr: '',
          wr: '',
        },
        {
          name: 'Stun Duration',
          amount: ['1s', '1s', '1s', '1s', '1s'],
          cr: '',
          wr: '',
        },
        {
          name: 'Charge Time',
          amount: ['1.6s', '1.6s', '1.6s', '1.6s', '1.2s'],
          cr: '',
          wr: '',
        },
        {
          name: 'Duration',
          amount: ['6s', '6s', '6s', '6s', '6s'],
          cr: '',
          wr: '',
        },
      ],
    },
    {
      name: 'OVERWHELM',
      type: 'B ABILITY',
      image: 'Yates-B',
      text: [
        'Yates gathers energy for 1.5s before releasing a shockwave around himself, stunning affected enemies.',
      ],
      video: 'Yates-B',
      stats: [
        {
          name: 'Cooldown',
          amount: ['10s', '9.5s', '9s', '8.5s', '8s'],
          cr: '',
          wr: '',
        },
        {
          name: 'Energy Cost',
          amount: ['25', '30', '35', '40', '45'],
          cr: '',
          wr: '',
        },
        {
          name: 'Damage',
          amount: ['140', '190', '240', '290', '390'],
          cr: '175%',
          wr: '140%',
        },
        {
          name: 'Range',
          amount: ['5.5', '5.5', '5.5', '5.5', '7.5'],
          cr: '',
          wr: '',
        },
        {
          name: 'Bonus Move Speed Duration',
          amount: ['3s', '3s', '3s', '3s', '3s'],
          cr: '',
          wr: '',
        },
        {
          name: 'Bonus Attack Speed',
          amount: ['40%', '40%', '40%', '40%', '40%'],
          cr: '',
          wr: '',
        },
        {
          name: 'Bonus Move Speed',
          amount: ['1', '1', '1', '1', '1'],
          cr: '',
          wr: '',
        },
        {
          name: 'Duration',
          amount: ['6s', '6s', '6s', '6s', '6s'],
          cr: '',
          wr: '',
        },
      ],
    },
    {
      name: 'IRON MANDATE',
      type: 'ULTIMATE',
      image: 'Yates-C',
      text: [
        'Yates leaps to the chosen location, dealing damage and slowing enemies while granting allies a barrier.',
        'Overwhelm will not disperse until Yates lands.',
        'Note: This is a global ability which means it can be casted anywhere in the map',
      ],
      stats: [
        {
          name: 'Cooldown',
          amount: ['25s', '20s', '15s'],
          cr: '',
          wr: '',
        },
        {
          name: 'Energy Cost',
          amount: ['50', '60', '70'],
          cr: '',
          wr: '',
        },
        {
          name: 'Damage',
          amount: ['300', '450', '600'],
          cr: '150%',
          wr: '',
        },
        {
          name: 'Trap Limit',
          amount: ['1', '1', '1'],
          cr: '',
          wr: '',
        },
        {
          name: 'Root Duration',
          amount: ['1.6s', '1.8s', '2s'],
          cr: '',
          wr: '',
        },
        {
          name: 'Bonus Attack Speed',
          amount: ['40%', '40%', '40%', '40%', '40%'],
          cr: '',
          wr: '',
        },
        {
          name: 'Bonus Move Speed',
          amount: ['1', '1', '1', '1', '1'],
          cr: '',
          wr: '',
        },
        {
          name: 'Duration',
          amount: ['6s', '6s', '6s', '6s', '6s'],
          cr: '',
          wr: '',
        },
      ],
    },
  ],
  talents: [
    {
      name: 'Extended Hooks',
      type: 'Rare',
      color: '#6393F9',
      text: [
        'Wolf’s Maw (A) has increased range.',
        '• Cooldown 110% (-2%)',
        '• Damage 75% (+5%)',
        '• Bonus Range 2.5 (+0.4)',
      ],
      image: 'Yates_Rare',
    },
    {
      name: 'Whiplash',
      type: 'Epic',
      color: '#7A02EA',
      text: [
        'Devastation Flail (Perk) third hit deals greatly increased damage.',
        '• Trap Limit 3',
        '• Damage 120%',
        '• Passive Attack Speed +0%',
        '• Bonus Range 6',
      ],
      image: 'Yates_Epic',
    },
    {
      name: 'Rapid Response',
      type: 'Legendary',
      color: '#FF9000',
      text: [
        'Iron Mandate (Ult) completes much more quickly.',
        '• Cooldown 60%',
        '• Damage 120%',
        '• Barrier 140%',
      ],
      image: 'Yates_Legendary',
    },
  ],
  skins: [
    {
      name: 'Crimson Wolf Yates',
      color: '#6393F9',
      type: 'Rare',
      price: '1200',
      image: 'Yates_CrimsonWolf',
    },
  ],
}
